### ISSUE TITLE
[BUG]: Hostname rejected when using a custom port

### ISSUE THREAD

**Issue by stanol** [azukaar/Cosmos-Server#10]
### What happened?

If I sigh in through cosmos ui (cosmos.example.com) end then open someservice.cosmos.example.com it works. But if I try to get access to someservice.cosmos.example.com when not logged in cosmos ui I get "Bad Request: Invalid hostname."

### What should have happened?

Login form should be displayed.

### How to reproduce the bug?

Enable Authentication Required for URL

### System details

- OS: Debian (Docker)
- Browser firefox
- Version v0.4.1

**Comment by stanol** [comment]
Now my hostname looks like cosmos.mydomain.com

**Comment by azukaar** [comment]
OK I think I almost understand the problem. I just need 2 more infos:
 - Do you use 80/443 or 8080 as your Cosmos port? 
 - Did you expose transmission with "transmission.cosmos.example.com:8080" in the "hostname" field?

**Comment by stanol** [comment]
Yes, I'm using port 8080.
Yes, host "transmission.cosmos.example.com:8080". This is how it was by default.
If remove port from host problem gone.

**Comment by azukaar** [comment]
Fixed in 0.4.2
