### ISSUE TITLE
[BUG]: emby reverse proxy

### ISSUE THREAD

**Issue by Serph91P** [azukaar/Cosmos-Server#100]
### What happened?

Cannot connect via emby connect but can connect via only the url just fine. 
Emby connect reports this error in the dev console: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

### What should have happened?

Emby connect can connect to the emby server.

### How to reproduce the bug?

Add the emby server and url to cosmos.
Settings in emby to allow certificate and external https port to be 443.
Can connect via url but not via emby connect.

### Relevant log output

```shell
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://redacted/emby/system/info/public. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' stimmt nicht mit 'add_header 'Access-Control-Allow-Origin' 'origin'' überein).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://172.17.0.3:8096/emby/system/info/public. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Cosmos itself just says: 28.09.2023
10:44:05
2023/09/28 08:44:05 "GET https://redacted/emby/system/info/public HTTP/2.0" from 217.24.203.178:56181 - 200 132B in 4.203615ms
```

### System details

- OS: does not matter
- Browser apps and chrome etc

**Comment by azukaar** [comment]
Can you send me the 2 URLS in Discord? THe one it's trying to access and the one that is actually in the header?
If it's trying to access itself it should be just fine normally

**Comment by Serph91P** [comment]
> Can you send me the 2 URLS in Discord? THe one it's trying to access and the one that is actually in the header? If it's trying to access itself it should be just fine normally

they are both the same url. Will send them in discord.

**Comment by Serph91P** [comment]
> Can you send me the 2 URLS in Discord? THe one it's trying to access and the one that is actually in the header? If it's trying to access itself it should be just fine normally

Issue still persists, where you able to look into it?
