### ISSUE TITLE
[FEAT]: WAF and HTTP support

### ISSUE THREAD

**Issue by dalso0418** [azukaar/Cosmos-Server#101]
### Feature Description

Hello. Thank you for the wonderful project.
Is it possible to support Mod Security WAF for web security?
Also, I wonder if HTTP3 is also supported.

**Comment by azukaar** [comment]
I didnt look into ModSecurity in details but it looks like a lot of it overlap with already implementing rules in the smart shield itself, so I am not sure?

HTTP3 will be supported as soon as Go fully supports it :)

Closing the ticket but feel free to keep the conversation going

**Comment by dalso0418** [comment]
Thank you for your reply.
I'm also looking forward to the monitoring capabilities.
It would be fantastic to be able to monitor traffic and block IPs recognized as malicious IPs through APIs.
