### ISSUE TITLE
[FEAT]: Custom registry for cosmos market

### ISSUE THREAD

**Issue by erdesigns-eu** [azukaar/Cosmos-Server#103]
### Feature Description

As a user i would like to be able to use a custom registry (like in protainer) so i can use my own images and install them from the cosmos market. Or the possibility to add multiple registries so people can share their registries so people can easily add new apps to the cosmos market.

**Comment by azukaar** [comment]
This is actually already implemented in the server, I just need to build the UI for it, whenever I get to it. Definitely a must-have

**Comment by azukaar** [comment]
added in 0.12
