### ISSUE TITLE
[FEAT]: Running Container Backups

### ISSUE THREAD

**Issue by spinningjenny69** [azukaar/Cosmos-Server#105]
### Feature Description

If i want to setup cosmos on a new server or transfer all my data to another instance for testing i have to setup everything manually again. 

I would like to save the config for easier deployment in the future and in the best case include the apps i have installed. The app data is not relevant, since i back that up anyways and for testing i want to start fresh

**Comment by azukaar** [comment]
Backing up the container list is indeed a planned feature, it will include performing the backup on a schedule and re-importing some or all of the containers back in the same, or another server

**Comment by azukaar** [comment]
added in 0.11
