### ISSUE TITLE
[BUG]: Cosmos container stuck on restarting since last update 

### ISSUE THREAD

**Issue by tarbib** [azukaar/Cosmos-Server#107]
### What happened?

Since last update (0.11.1) I cannot reach my server:
"Unable to connect" from my browser.
I checked cosmos-server logs and last ones are:
`2023/10/22 18:49:43 [INFO] Starting...
2023/10/22 18:49:43 [INFO] Using config file: /config/cosmos.config.json
2023/10/22 18:49:43 [INFO] Validating config file...
2023/10/22 18:49:43 [INFO] Docker Connected
panic: strconv.Atoi: parsing "penpot": invalid syntax

goroutine 1 [running]:
github.com/azukaar/cosmos-server/src/docker.ExportDocker()
	/home/circleci/project/src/docker/export.go:151 +0x1459
main.main()
	/home/circleci/project/src/index.go:26 +0x1ac`

### What should have happened?

I should be able to access my Comos server ;) 

### How to reproduce the bug?

1. Go to 'mydomain.tld'
2. See error

### System details

- OS: Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-165-generic x86_64)
- Browser: Firefox

**Comment by tarbib** [comment]
So I Docker stopped all containers linked to penpot
Then Docker rm all stopped containers
then Docker system prune followed by reboot and it's back online

**Comment by azukaar** [comment]
There was an issue in 0.11.0 causing a crash with some exotic container syntax (using non-id users definitions)
I quickly fixed it in 0.11.1 sorry for the inconvenience :)
