### ISSUE TITLE
[FEAT]: Storage Manager

### ISSUE THREAD

**Issue by Draxter** [azukaar/Cosmos-Server#110]
### Feature Description

As a Cosmos user, I want to be able to manage storage on my NAS, so that I can create and operate on my computer's NAS storage system.

**Features that I would expect:**
- View storage devices
- Create a basic storage pool on a single drive
- Create an advanced RAID/ZFS/BTRFS redundant storage pool
- Create/manage storage pool snapshots
- View pool health
- Destroy a storage pool

**Limitations/Challenges:**
- Cosmos would need to be running with the `--privileged` flag
- There would need to be checks on what types of RAID the OS is capable of based on number of devices
- Check whether ZFS kernel module is installed

**Comment by azukaar** [comment]
Thanks for the (well written :) ) ticket!
Yes Storage is one of the next to go, I am not 1000% about how deep the RAID/... family I want to implement, but at the very least it will allow some of it. It needs more research to evaluate complexity of integration (especially compatibility as you mentioned but also error management, recovery, etc... For example if I implement RAID I need to implement all scenario like replacing a disk)

**Comment by spuder** [comment]
Also looking forward to this. 

For `raid` consider looking at [cockpit](https://cockpit-project.org/) documentation (it uses existing apis which cosmos might be able to implement)
For `btrfs` consider looking at [rockstor](https://rockstor.com/linux-btrfs-nas-server.html) documentation

Also consider looking at [MergerFS](https://github.com/trapexit/mergerfs) as it is very light weight and the core developer is active in the CasaOS community discord.

**Comment by azukaar** [comment]
Added to 0.15
