### ISSUE TITLE
[BUG]: SERVFAIL when setup DNS Challenge with GandiV5

### ISSUE THREAD

**Issue by cedatif** [azukaar/Cosmos-Server#114]
### What happened?

When I tried to setup the DNS Challenge with GandiV5, I use my personal access token and I have a `SERVFAIL` error.

`acme: error presenting token: gandiv5: could not find zone for domain "example.exeample.com" (_acme-challenge.example.exeample.com.): unexpected response code 'SERVFAIL' for _acme-challenge.example.exeample.com. `

### What should have happened?

No error

### How to reproduce the bug?

1. Generate a personal access token on GandiV5
2. Paste your personal access token in the DNS challenge section
3. Save

### Possible solution

Maybe change the name of the environment variable to `GANDIV5_PERSONAL_ACCESS_TOKEN` instead of `GANDIV5_API_KEY`

### System details

- OS: MacOS Ventura
- Version: 0.11.3

**Comment by azukaar** [comment]
Gandi support fixed in 0.15
