### ISSUE TITLE
[BUG]: Terminal TTY input bug

### ISSUE THREAD

**Issue by SSTentacleSS** [azukaar/Cosmos-Server#117]
### What happened?

When I connect to the TTY of a process - although the text in DevTools is transferred to the TTY, but it does not show that I am typing anything

![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/f82e4598-9eaa-45f0-af1f-ad07d68b060c)

### What should have happened?

Text should appear in text input

### How to reproduce the bug?

1. Install Minecraft (for example) from Market with default configuration
2. Connect to Minecraft TTY (Home/ServApps/Minecraft/Terminal > Connect)
3. Write anything

### System details

- OS: Desktop 6.5.5-1-MANJARO, Server 6.5.9-1.el9.elrepo.x86_64
- Browser: Brave (Chromium-based web browser)
- Versions: Latest Cosmos, Latest Brave browser

**Comment by SSTentacleSS** [comment]
Oh, it's just such a dark font, I'm sorry, I only noticed it after looking closely 😂

**Comment by azukaar** [comment]
Are you using anything that would affect the color? By default it is white

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/b8b778f7-1fda-4ee8-821b-5ca99ca0180e)

**Comment by SSTentacleSS** [comment]
> Are you using anything that would affect the color? By default it is white
> 
> ![image](https://user-images.githubusercontent.com/7872597/278811304-b8b778f7-1fda-4ee8-821b-5ca99ca0180e.png)

I don’t know what could affect it, I don’t use any plugins, all the themes were loaded the same way the first time after installation, I didn’t change anything

**Comment by SSTentacleSS** [comment]
Same thing with newly installed Firefox

![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/53ada0ea-b3be-4e5a-acd7-8d79306b3963)

**Comment by SSTentacleSS** [comment]
DevTools says there is a color override

![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/03a13596-8ca1-4c00-a975-29c3ec241063)

**Comment by azukaar** [comment]
fixed in 0.15
