### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by styl3hack** [azukaar/Cosmos-Server#120]
### What happened?

Can't get the server to run on Ubuntu
Error Validating config file.

### What should have happened?

The Server should Start

### How to reproduce the bug?

after the setup is finished and the server restarts

### Relevant log output

```shell
[INFO] Starting...
2023/10/29 09:39:18 [INFO] Using config file: /config/cosmos.config.json
2023/10/29 09:39:18 [INFO] Validating config file...
2023/10/29 09:39:18 [FATAL] Reading Config File: Key: 'Config.HTTPConfig.Hostname' Error:Field validation for 'Hostname' failed on the 'excludesall' tag : Key: 'Config.HTTPConfig.Hostname' Error:Field validation for 'Hostname' failed on the 'excludesall' tag
```

### System details

- OS: Ubunutu 22.04 & 23.10

**Comment by azukaar** [comment]
You have input a wrong hostname during install
can you show us your config file?
/var/lib/cosmos.config.json
