### ISSUE TITLE
[FEAT]: Automatic resizing of icons

### ISSUE THREAD

**Issue by SSTentacleSS** [azukaar/Cosmos-Server#121]
### Feature Description

Is it possible to add a mechanism so that the cosmos client changes the resolution of images? It's quite difficult to load your own version of an icon, but if the icon is too big it will break the ServApps UI

![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/6aa9849a-0e19-4299-87ef-05995517ee80)

**Comment by azukaar** [comment]
yes this icon component needs  a bit of rework I agree

**Comment by azukaar** [comment]
fixed in 0.12
