### ISSUE TITLE
[BUG]: Extra endlines in the Terminal

### ISSUE THREAD

**Issue by SSTentacleSS** [azukaar/Cosmos-Server#123]
### What happened?

When I use the terminal - there are often empty spaces that appear immediately after the end of a line (not every one)

Terminal
![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/4df74543-aeaf-4a80-942d-f7a7881550bf)

Logs
![image](https://github.com/azukaar/Cosmos-Server/assets/91948148/18add27f-5ff1-46a2-a0bd-bb0fb32f6ade)

### What should have happened?

In theory, I would like there to be no extra lines, as for example done in Logs

### How to reproduce the bug?

1. Install minecraft from Market
2. Type /help in Terminal

### System details

- OS: 5.14.0-284.30.1.el9_2.x86_64
- Browser: Brave (Chromium based)
- Version: Latest Cosmos, Latest Brave, Kernel 5.14

**Comment by SSTentacleSS** [comment]
I think it’s time to introduce limits on the number of simultaneous open Issues especially for me 😅

**Comment by azukaar** [comment]
The whole terminal UI needs a lift-up for sure

**Comment by azukaar** [comment]
fixed in 0.15
