### ISSUE TITLE
[QUESTION]: Private docker registry

### ISSUE THREAD

**Issue by Kawanaao** [azukaar/Cosmos-Server#124]
How can I log in to the container registry in order to pick up a container from there?
docker login doesn't work cause cosmos gives an error

```
[ERROR] Rolling back changes because of -- Image pull error: Error response from daemon: unauthorized: authentication required
```

**Comment by azukaar** [comment]
You need to `docker login` on your daemon, Cosmos pulls your auth from it so it should work

**Comment by Kawanaao** [comment]
> You need to `docker login` on your daemon, Cosmos pulls your auth from it so it should work

It looks like cosmos is ignoring the authorization I made on the host..

![image](https://github.com/azukaar/Cosmos-Server/assets/149584315/172a30da-a28a-405e-9d8b-46827170fe2d)

![image](https://github.com/azukaar/Cosmos-Server/assets/149584315/8b998971-f243-41af-a137-85b1ba73e03f)

**Comment by Kawanaao** [comment]
### Update
Cosmos cannot interact with data located in the local storage of another user, I tried using /bin/sh in the cosmos-cloud container to create a file `/root/.docker/config.json` manually indicating all the data that is specified in the same file on the host and pull was successful

![image](https://github.com/azukaar/Cosmos-Server/assets/149584315/e2df4b7b-5cbe-42f8-b661-8a2c34ef7510)

Perhaps it's worth adding this as part of the documentation? As a warning or option -v $HOME/.docker:/root/.docker

**Comment by dragons-library** [comment]
To elaborate on this, I did the following...
```
# within the cosmos-server container shell...
docker exec -it cosmos-server bash

# create a directory `/root/.docker`
mkdir -p /root/.docker

# exit the container shell
exit

# copy the local `/root/.docker/config` to the container
docker cp /root/.docker/config.json cosmos-server:/root/.docker/
```

A longer term solution would probably be to map the path in the `cosmos-server` container
