### ISSUE TITLE
[BUG]: MongoDB failed to install

### ISSUE THREAD

**Issue by sureshfizzy** [azukaar/Cosmos-Server#129]
### What happened?

MongoDB is failing on new install

### What should have happened?

MongoDB container should be installed and started

### How to reproduce the bug?

1. deploy new docker image (docker run -d -p 80:80 -p 443:443 -p 4242:4242/udp --privileged --name cosmos-server -h cosmos-server --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /:/mnt/host -v /var/lib/cosmos:/config azukaar/cosmos-server:latest)
2. cosmo server wont start

### Relevant log output

```shell
2023/11/09 13:56:02 [ERROR] Metrics - Database Connect : MongoDB URL is not set, cannot connect to the database.

2023/11/09 13:56:02 [INFO] Metrics: Agglomeration done. Saving to DB

2023/11/09 13:56:02 [INFO] (Re) Connecting to the database...

2023/11/09 13:56:02 [ERROR] Metrics - Database Connect : MongoDB URL is not set, cannot connect to the database.
```

### System details

- OS: Ubuntu 22.04.3 LTS aarch64
- Machine: AMD64

**Comment by azukaar** [comment]
Until you have finished the installer it is  normal that  it cannot connect to the DB

**Comment by danielo515** [comment]
In my case the database is failing to start.
Any suggestion about how to fix that?
```
ERROR: child process failed, exited with 51
To see additional information in this output, start without the "--fork" option.
warning: initdb logs cannot write to '/proc/1/fd/1', so they are in '/data/db/docker-initdb.log' instead
about to fork child process, waiting until server is ready for connections.
forked process: 27
ERROR: child process failed, exited with 51
To see additional information in this output, start without the "--fork" option.
warning: initdb logs cannot write to '/proc/1/fd/1', so they are in '/data/db/docker-initdb.log' instead
about to fork child process, waiting until server is ready for connections.
forked process: 27
```

**Comment by azukaar** [comment]
This is a MongoDB thing I suggest checking their forum: https://www.mongodb.com/community/forums/t/error-child-process-failed-exited-with-error-number-51/230721

**Comment by danielo515** [comment]
Nevermind, I updated to ubuntu 18, then updated docker and it worked.
Maybe the installer should check some minimums in versions
