### ISSUE TITLE
[FEAT]: SSO Middleware: Support HTTP Basic Authentication

### ISSUE THREAD

**Issue by markcs** [azukaar/Cosmos-Server#13]
### Feature Description

Some mobile apps only support HTTP Basic Authentication (ie using username:password@myserver.com), which is likely also the authentication method used by the applications that they support.  

So that I can control users/passwords in one place, it would be great if Cosmos supported this authentication method for apps.

(as discussed on Discord, but here for tracking)

**Comment by AlexanderEDavis** [comment]
Would it be possible to this to also include header authentication? I know the *arr apps require both basic browser popup and header authentication

**Comment by azukaar** [comment]
Applications supporting HTTP basic auth will have their own implementation, so no need to add it in Cosmos itself (ex. Radarr has its own HTTP basic auth)
Cosmos already has header-auth (x-cosmos-user)
