### ISSUE TITLE
[BUG]: Paperless-ngx fails to install

### ISSUE THREAD

**Issue by repercussion** [azukaar/Cosmos-Server#137]
### What happened?

Trying to install paperless-ngx by just clicking the buttons. Nothing out of the ordinary. 

### What should have happened?

It should haave installed

### How to reproduce the bug?

1. Go to Market
2. Click on Paperless-ngx 
3. Click on Install 

### Relevant log output

```shell
[ERROR] Rolling back changes because of -- Container creation error: Error response from daemon: No such image: ghcr.io/paperless-ngx/paperless-ngx:latest

[ERROR] Rollback: Network Error response from daemon: network Paperless-ngx-network not found[OPERATION FAILED]. CHANGES HAVE BEEN ROLLEDBACK.
```

### System details

- OS: lxc debian bookworm in pve 8
- Browser Firefox 119.0.1
- Version 0.12.6

**Comment by azukaar** [comment]
Thanks for reporting it will be investigated :)

**Comment by azukaar** [comment]
Paperless seems to install fine, have you tested other apps? May be some networking issue on your setup?

**Comment by mattokar** [comment]
Hello. I would like to reopen this issue. Paperless fail to install, but different error this time.

```
[ERROR] Rolling back changes because of -- Volume creation error: Error response from daemon: create -broker-pgdata: "-broker-pgdata" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

**Comment by azukaar** [comment]
You're missing a service name

**Comment by mattokar** [comment]
oh my god. sorry. I am just figuring out/getting to know cosmos

**Comment by azukaar** [comment]
np!
