### ISSUE TITLE
Existing Lets encrypt certificates

### ISSUE THREAD

**Issue by andonovski** [azukaar/Cosmos-Server#14]
I already have Linuxserver's SWAG docker container running, NGINX with Lets encrypt certificates automation. All working fine, using DNS validation (Cloudflare DNS).

Now, I am wondering is it possible to "migrate" from SWAG to Cosmos reverse proxy and Lets encrypt, the Lets encrypt part actually. Not just to move existing certificates, but to be sure that they will be renewed.

Cheers

**Comment by azukaar** [comment]
Basically Let's Encrypt certificates are quite volatile and immutable. You don't need to "migrate them" as, as soon as you migrate your server to Cosmos, it will request new certificate using the same DNS challenge mechanism and Let's Encrypt will happily comply. Your old SWAG certificates will then become invalid
