### ISSUE TITLE
[HELP]: High network usage of cosmos-server

### ISSUE THREAD

**Issue by victorenaud** [azukaar/Cosmos-Server#142]
Hi,
I just installed Cosmos Server today on my Raspberry, and everything was fine.
I only added home-assistant, without doing nothing more (not even configuring it), and haven't changed setup configuration (where I added my domain and let's encrypt).

3 hours later, without doing anything, I noticed an uptick in network usage.
In less than a hour, Cosmos-Server sent ~150Mb and received ~100Mb.
While before it was only around ~1Mb for both.

Is it normal for Cosmos-Server to have such a high network consumption suddenly?
I tried removing all automatic updates, rebooting the raspberry as well as the containers, to no avail.

**Comment by azukaar** [comment]
Cosmos network usage is always going to be very high, it is your reverse proxy. All the network of all your container will go throught Cosmos, it is quite natural to see high usage. You should be able to cross reference that network usage to other container's own usage (ex if you have 150mb on Cosmos you should have 150mb of total usage on the other containers) this is an example, here, I have 2.7gb on Cosmos, but that actually matches the sum of all the other container's network:

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/9f21684d-f230-4f24-aca2-1abef8279c1f)

**Comment by victorenaud** [comment]
Thanks for the clarification.
I did not see any correlation between the cosmos-server usage and the others containers usage.

I have much more usage on cosmos-server, than on all the others containers. :thinking: 
![image](https://github.com/azukaar/Cosmos-Server/assets/7222886/85ec5c24-f7b3-422f-809b-6bfa3313574a)

**Comment by azukaar** [comment]
In your screenshot Mongo has transmitted 120mb, Cosmos has received 135mb, that's where most of it come from
then it transmitted 200mb which correspond to you previewing that data in the browser, guess you've been playing around with the dashboard a lot
