### ISSUE TITLE
[BUG]: Error with Emby Install

### ISSUE THREAD

**Issue by TekNicholas** [azukaar/Cosmos-Server#144]
### What happened?

When attempting to install Emby I receive the following error:
JSON.parse: expected double-quoted property name at line 42 column 7 of the JSON data

### What should have happened?

Expected install to commence.

### How to reproduce the bug?

    Go to Market
    Click on Emby
    Click on Install
    Error is reported and install ceases.

Seems to also happen on the demo at https://cosmos-cloud.io/cosmos-ui/market-listing/cosmos-cloud/Emby

### Relevant log output

```shell
JSON.parse: expected double-quoted property name at line 42 column 7 of the JSON data
```

### System details

- OS: Linux (Debian 12.2.0) 
- Browser: Firefox
- Cosmos version: 0.12.6

**Comment by azukaar** [comment]
Fixed thanks :)
