### ISSUE TITLE
Podman install

### ISSUE THREAD

**Issue by laguill** [azukaar/Cosmos-Server#148]
### Feature Description

Hello,
I am beginner and I have seen a lot of talking around podman.
Is it better do use podman over docker ?
Is it possible to do the install process with podman ?

**Comment by azukaar** [comment]
Docker is the recommended way to go especially for a beginner since Podman would be a bit more difficult to setup.
In the future if you want to have more of a conversation style request, dont hesitate to come visit the Discord :)
