### ISSUE TITLE
[HELP]:  Editor of WordPress 

### ISSUE THREAD

**Issue by Elcasano** [azukaar/Cosmos-Server#158]
### What happened?

I have installed WordPress. But I can not find visual editor. It is only have "text" with html tags

### What should have happened?

I try install some editor plugin but nothing change

### System details

Wordpress CMS

**Comment by azukaar** [comment]
Sorry to hear you're having trouble
this section is used to discuss bugs on Cosmos specifically, feel free to come discuss other subjects on the Discord with the community
