### ISSUE TITLE
[BUG]: lets encrypt cert error

### ISSUE THREAD

**Issue by Solain** [azukaar/Cosmos-Server#160]
### What happened?

I tried to set up cosmos server for the first time, using a domain from duckdns (after I configured it in my modem accordingly and opened ports and reserved an ip for my server + making it static).

 I did try to setup the server with a different domain before ( which also worked) but than changed to duckdns.

I also configured the challange in the options with the duckdns token.

But when I login the home page shows the folling message with a red exlamation mark, and the wbsite has an invalid certificate:

There are errors with your Let's Encrypt configuration or one of your routes, please fix them as soon as possible:
- error: one or more domains had a problem: [solain.duckdns.org] propagation: time limit exceeded: last error: read udp 172.17.0.2:50175->15.222.19.97:53: i/o timeout 

### What should have happened?

The website should have a proper ssl cert and not show the error. 

### How to reproduce the bug?

1. Setup cosmos server
2. Cli

### System details

- OS: debian
- Browser chrome+firefox

**Comment by azukaar** [comment]
As written in the Let's Encrypt documentation linked in the setting page of Cosmos for your specific provider, you need to extend the timeout time by setting an environment variable (depends on the provider) to a higher value
Don't hesitate to research non-cosmos answers to those Let's encrypt errors as the answers will remain true (I did not implement LE juste used a standard library to handle it)

**Comment by Solain** [comment]
Just for future reference, I fixed it by using the wildcard cert, I found no eay to set env variables as lego shows as not installed in bash.
