### ISSUE TITLE
[FEAT]: Multiple Domains

### ISSUE THREAD

**Issue by lzinga** [azukaar/Cosmos-Server#166]
### Feature Description

It would be a great addition to be able to support multiple domains, that way you do not need to have two servers running for multiple potential websites.

**Comment by azukaar** [comment]
You can add multiple domains by creating URLs for them, it will work

**Comment by lzinga** [comment]
> You can add multiple domains by creating URLs for them, it will work

How would that work with the LetsEncrypt certificate grabber? It would still be beneficial to look into and make it so you can add multiple domains in the setup and set them up for certificates. That and it would allow a dropdown when creating a new app to select which domain you want to host the service on.

**Comment by azukaar** [comment]
When you do the setup you only set the Cosmos domain
then when you add new URL you can set whatever domain you want, there's no restrictions in the setup

If you use Let;s Encrypt:
 - With TLS challenge: it will work just like that and will get a multi-domain cert
 -  With DNS challenge you need to amke sure that the token provided has authority on both domain
