### ISSUE TITLE
[FEAT]: Custom Icons

### ISSUE THREAD

**Issue by AE720** [azukaar/Cosmos-Server#175]
### Feature Description

It would be a nice QOL, if, when you're in the settings or a URL, you can just click on the picture and have the ability to add any icon you prefer, especially on the off chance Cosmos isn't able to pick up on what icon it's supposed to use. I know OpenWRT doesn't seem to properly give out it's favicon

**Comment by azukaar** [comment]
You can do it on servapps, which is what URL icons are based on
