### ISSUE TITLE
[FEAT]: Multiple hostnames

### ISSUE THREAD

**Issue by QazCetelic** [azukaar/Cosmos-Server#179]
### Feature Description

As a user, I want to add multiple hostnames to Cosmos, so I can access the Cosmos management UI through my local network or DNS hostname record when using my mesh VPN.

**Comment by azukaar** [comment]
do you mean vpn.domain.com? 
you can use your domain name in your local network too

or do you mean to access the cosmos UI

**Comment by QazCetelic** [comment]
I meant the Cosmos UI

**Comment by azukaar** [comment]
In your local network you can use the same domain as  external
inside the mesh VPN simply use the embedded DNS to rewrite the IP of the main domain to a tunneled IP
