### ISSUE TITLE
[BUG]: Debian 11 + Docker-Compose is broken

### ISSUE THREAD

**Issue by infmatematicas** [azukaar/Cosmos-Server#18]
### What happened?

Hi, when letting cosmos 0.5.12 create a mongodb by itself, it currently creates 2 mongodb containers and the initial admin user it prompts to create doesn't let you log in. if you provide your own mongodb it will work fine.

### What should have happened?

It should have worked

### How to reproduce the bug?

create a new comsos server

### System details

- Version 0.5.12

**Comment by azukaar** [comment]
Are you using Debian 11?
if yes try creating your cosmos instance without Docker-compose,
it's a known bug with whatever setup of DC there is in that distro

**Comment by infmatematicas** [comment]
Yes, as a matter of fact it was Debian 11. I just tested it out without docker compose and it works great! Thank you very much.
