### ISSUE TITLE
Network Page Screen Flashing

### ISSUE THREAD

**Issue by andersonrochabh** [azukaar/Cosmos-Server#180]
### What happened?

When ai click on Serverapps, Networks , the screen flash and i cant see or click anymore... I tested on Chrome, Edge, Firefox anda Vivaldi with no success... This happened with apss too. I am accessing by Windows 11 machine

### What should have happened?

When i clcked on Networks the configuration screen must be visible.

### How to reproduce the bug?

1. Go to Servapps
2. Click on 'Network
3. See error... Nothing is viewed

### System details

- OS: Debian 11
- Browser Chorme, Edge, Vivaldi
- Version Lastests

**Comment by azukaar** [comment]
Can you open the browser console (F12) and see what error appear please?

**Comment by andersonrochabh** [comment]
> Can you open the browser console (F12) and see what error appear please?

No error...
![image](https://github.com/azukaar/Cosmos-Server/assets/92112499/8089eafb-6c33-4776-9dd4-2fe6f31103ba)

I can access the Network setup if  iminimize the window, (Sorry my bad english)

**Comment by azukaar** [comment]
Apologies for the lack of clarity the error is here
![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/ce98fff6-1aef-48a1-b4b3-b228bd49e849)

**Comment by andersonrochabh** [comment]
![image](https://github.com/azukaar/Cosmos-Server/assets/92112499/cfae11d7-e737-4c64-bc3b-fed576c05561)

**Comment by azukaar** [comment]
Thanks I implemented the fix in next version

**Comment by azukaar** [comment]
Fixed in 0.13
