### ISSUE TITLE
[BUG]: Subdirectory URLs not working

### ISSUE THREAD

**Issue by 4abhinavjain** [azukaar/Cosmos-Server#181]
### What happened?

Cosmos looks very promising and I am thinking of switching from Caprover. However, I would like to use subdirectories for different services instead of subdomain. 

### What should have happened?

Routes for subdirectories should work normally.

### How to reproduce the bug?

1. I tried deselecting "use host" and defined a "path prefix" as a subdirectory. However, when I visit the site, I get "Not found. Go to default page".

![image](https://github.com/azukaar/Cosmos-Server/assets/34500467/a028584e-b9da-47f3-aa0b-4112230f76ac)

2. If I select "Strip path prefix" and "use host" (which I use the same hostname as the one for cosmos) then it works partially:

![image](https://github.com/azukaar/Cosmos-Server/assets/34500467/e993045e-12bf-4884-afc6-13459121062b)

![image](https://github.com/azukaar/Cosmos-Server/assets/34500467/c5fdc59f-5034-41ca-9b5e-b1ccc41b7cd2)

3. Could anyone guide if it is some mistake or bug, or subdirectories are not supported (I recall that some dockerized services does not support subdirectories)?

### System details

- OS: Ubuntu in LXD
- Browser: tried both in Vivaldi and Edge

**Comment by azukaar** [comment]
Unfortunately it's up to individual application to support (or not) being in a subpath. If they do, usually a setting is avaialble to tell it what subpath to support. There is really nothing that can be done about this at Cosmos level
