### ISSUE TITLE
[BUG]: Code-Server container error

### ISSUE THREAD

**Issue by DavidHur** [azukaar/Cosmos-Server#182]
### What happened?

When it is installed then open the browser

### What should have happened?

Pop up the message as below;
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: "//{{port}}.192.168.0.24:7205" cannot be parsed as a URL.)
![IMG_5211](https://github.com/azukaar/Cosmos-Server/assets/3503509/e05ae3e6-cac1-4eba-a62a-df8f1d26931f)

### How to reproduce the bug?

1. Open the Code-Server browser
2. Showing error message 
3. Then Click on reload button
4. Reload again and error message popup again.

### Relevant log output

```shell
2024-01-20 16:59:13
 File not found: /app/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
2024-01-20 16:59:13
 File not found: /app/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
2024-01-20 16:59:20
 File not found: /app/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
2024-01-20 16:59:20
 File not found: /app/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
```

### System details

- OS: Arch linux
- Browser : chrome & safari
- Version : latest

**Comment by azukaar** [comment]
Can you go to the containers details in the servapp page and tell me what the env var look like please?

**Comment by DavidHur** [comment]
<img width="970" alt="스크린샷 2024-01-22 오전 1 42 11" src="https://github.com/azukaar/Cosmos-Server/assets/3503509/988e95f8-234f-47a8-9eba-c7c0a5cca2a3">

Thanks for your help and this is great!

**Comment by azukaar** [comment]
Unfortunately the app itself does not seem to support being proxied without a domain (using an IP/port). You can either
 - get a domain
 - use a virtual hostname / domain (something like constellation / pihole offers)
 - expose the app directly with no proxy
 
And optionally you can open a ticket with the original app to try to get it supported
