### ISSUE TITLE
Vaultwarden Installation Error

### ISSUE THREAD

**Issue by andersonrochabh** [azukaar/Cosmos-Server#183]
### What happened?

i cant install Vauktwarden

### What should have happened?

Install the Vaultwarden

### How to reproduce the bug?

1. Go to Market
2. Click on 'Vaultwarden, Install
3. See error:

![image](https://github.com/azukaar/Cosmos-Server/assets/92112499/03dea240-9b78-4138-8915-5c096000a8d1)

### System details

- OS:Debian 11
- Browser Edge, Chrome, Vivaldi
- Version Lastests

**Comment by azukaar** [comment]
Maybe some intermittent network issue on your end as I cannot reproduce this issue. Try restarting Cosmos (button on the setting page)

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/bfefd6bf-a5f0-4d53-871e-3acfc3da2a2a)
