### ISSUE TITLE
[BUG]: Internal server error: lookup

### ISSUE THREAD

**Issue by sclaren** [azukaar/Cosmos-Server#185]
### What happened?

- I have installed Cosmos on a Rasperry 4 with DietPi as OS.
- I set the Hostname of the PI Host to home.pi
- I set the Hostname in Cosmos to home.pi
- I have a second Raspberri installed which makes the DNS rewrite in my local network. I configured it to map home.pi to the IP of the Cosmos Host
- I can use Cosmos Server with that URL (https://home.pi) without any issues. So it works in general.

But: When I install an App (for example Actual) it says:  lookup Internal server error: lookup actual.home.pi on 127.0.0.11:53: no such host. actual.home.pi or *.home.pi did not fix it. 

I tried to find an setting to set an upstream DNS or config DNS Settings, but did not find anything

### What should have happened?

When I use a local hostname, Cosmos Server should be able to resolve the Host Name correctly

### How to reproduce the bug?

see above

**Comment by azukaar** [comment]
Cosmos uses the local resolver to check the DNS entry.
If Cosmos does not see the entry made in your local DNS, it means the Cosmos container is not using your custom DNS

**Comment by aroldobossoni** [comment]
> Cosmos uses the local resolver to check the DNS entry. If Cosmos does not see the entry made in your local DNS, it means the Cosmos container is not using your custom DNS

I couldn't find a solution to this problem in the Cosmos panel or in the application.
Or I didn't really understand what the problem is.
