### ISSUE TITLE
[BUG]: Connection Refused 

### ISSUE THREAD

**Issue by Reledia** [azukaar/Cosmos-Server#187]
### What happened?

Premise: Im very noob when it comes to web stuff.
I set up the server apparently in the correct way. I can connect to it from my own domain. The problem comes when I try to install a new app from the store (which does) and open the link for it (changing from app.domain to domain.xyz/app as I dont understand how to set up the first option): the link works, but it loads only the text, and the images saying that the connection was refused. I read the docs and issues multiple times but I find no trace of anything similar

![image](https://github.com/azukaar/Cosmos-Server/assets/82183718/f093d1b5-02c3-4439-87f1-9f23750752c2)

### What should have happened?

The install should have provided a usable link without additional debugging/steps

### How to reproduce the bug?

1. Go to 'marketplace.'
2. Install 'StirlingPDF'
3. Open link
4. See errors

### Relevant log output

This is the only thing relative to Stirling when loading the url:
```shell
2024/01/26 04:18:10 "GET https://domain.xyz/stirling-pdf HTTP/2.0" from 192.168.1.1:34478 - 200 81619B in 7.825576ms   
```

### System details

- OS: EndeavourOS Linux x86_64, Linux 6.7.0-3-cachyos
- Browser vivaldi/firefox
- Version 6.5.3206.55/107.0b9

**Comment by azukaar** [comment]
Most apps wont support doing domain.com/abc, nothing can be done about this.
To setup abc.domain.com, you need to add entries in your DNS for those subdomains (or *.domain.com). Note that it will require a full domain name (it wont work with the free dyndns like no-ip.org)

**Comment by Reledia** [comment]
Thanks, I managed to setup the links in the right way and now I can use both apps from the store and from my own composes without problems
