### ISSUE TITLE
[BUG]: Vandam has changed named to Manyfold. Image must be updated.

### ISSUE THREAD

**Issue by chip-davis** [azukaar/Cosmos-Server#188]
### What happened?

Love Cosmos server! Just installed and noticed that Vandam has changed, as seen [here](https://github.com/manyfold3d/manyfold), Vandam has changed their name to Manifold. Upon entering the site, we are given a warning that the name has changed and in order to continue to receive updates, the image must be changed to `ghcr.io/manyfold3d/manyfold`

### What should have happened?

The Vandam image / name in the Market should be swapped to reflect this.

### How to reproduce the bug?

1. Go to Market
2. Click on Vandam
3. Install
4. Open page
5. See message telling you to switch

### System details

N/A

**Comment by Floppy** [comment]
Hello! I'm the developer of Manyfold, and I've just come across Cosmos Cloud, then was amazed to see that people are running my code on it 😁 

Is there anything I can do to help make the change? I'm not familiar with the way apps are defined, but I'm happy to make whatever change required, and add Cosmos to the list of installation methods at https://manyfold.app/get-started/

**Comment by azukaar** [comment]
> Is there anything I can do to help make the change?

Welcome @Floppy ! :)
Yes that would be our honor! There is a compose file here:
https://github.com/azukaar/cosmos-servapps-official/tree/master/servapps/Van_DAM

With a description file and a screenshot folder. It works almost the same as the normal yml compose except it's in json a has 1 or 2 additional features (but the API is the same). If you can make the amend on that folder I will happily merge it!

**Comment by Floppy** [comment]
Ah, superb! Will do :)
