### ISSUE TITLE
Allow Tag Flags on URLs

### ISSUE THREAD

**Issue by AlexanderEDavis** [azukaar/Cosmos-Server#189]
### Feature Description

It would be great to allow the use of tags for URLs on the server and when looking at the Home Screen each tile has the tags appear on them similar to how [Homer](https://homer-demo.netlify.app/) uses tags

**Comment by azukaar** [comment]
I will implement categories eventually but I am not quite sure the value individuals tags are... especially since tags are just categories if you have one tag only (which seems to be the case in that demo)
