### ISSUE TITLE
[BUG]: Discourse ServApp - Proxy Response Discourse Error

### ISSUE THREAD

**Issue by rjrmills** [azukaar/Cosmos-Server#191]
### What happened?

Fresh standalone Cosmos install on Debian 12 LXC. Discourse ServApp not connecting due to:
`{
  "id": "65c8088013607bf106592566",
  "label": "Proxy Response Discourse error",
  "application": "Cosmos",
  "eventId": "cosmos.proxy.response.Discourse.error",
  "date": "2024-02-10T23:36:22.208Z",
  "level": "warning",
  "data": {
    "bytes": 0,
    "clientID": "::1",
    "method": "GET",
    "route": "Discourse",
    "status": 502,
    "time": 0.000058239,
    "url": "/assets/workbox-84721eb2561c34fa8575f276d429c215/workbox-expiration.prod.js"
  },
  "object": "route@Discourse"
}`

### What should have happened?

Can not connect to front end due to internal proxy error

### Relevant log output

```shell
{
  "id": "65c8088013607bf106592566",
  "label": "Proxy Response Discourse error",
  "application": "Cosmos",
  "eventId": "cosmos.proxy.response.Discourse.error",
  "date": "2024-02-10T23:36:22.208Z",
  "level": "warning",
  "data": {
    "bytes": 0,
    "clientID": "::1",
    "method": "GET",
    "route": "Discourse",
    "status": 502,
    "time": 0.000058239,
    "url": "/assets/workbox-84721eb2561c34fa8575f276d429c215/workbox-expiration.prod.js"
  },
  "object": "route@Discourse"
}
```

**Comment by azukaar** [comment]
The Discourse server takes a long time to start, wait for it to complete initialization
