### ISSUE TITLE
[BUG]: Geo-Blocking doesn't work

### ISSUE THREAD

**Issue by Seeker14491** [azukaar/Cosmos-Server#192]
### What happened?

Geo-Blocking doesn't seem to be working at all.

### What should have happened?

Geo-Blocking should prevent connecting to the server from certain countries.

### How to reproduce the bug?

I set the Geo-Blocking to whitelist mode, and set "United States" as the only country to allow. However, testing through a VPN, I can successfully log into the server from Japan and the Netherlands. I also tried using blacklist mode instead, but again it didn't have any effect in preventing me from logging into the server.

### System details

- OS: Ubuntu 22.04.3 running in WSL2
- Browser: Firefox Developer Edition
- Cosmos Version: 0.14.3

**Comment by azukaar** [comment]
Geo Blocking definitely work (just retested it to be sure :) )
if yours doesnt:
- make sure your request is actually going through your VPN
- make sure Cosmos can see the incoming IP properly (wont work behind CF Proxy, wont work in WSL, .....)

Check the cosmos logs to make sure the IP / country incoming is what you expect

**Comment by Seeker14491** [comment]
Ah, I am running Cosmos inside WSL2, so that must be the issue. I think adding this information to the Geo-Blocking docs is a good idea.
