### ISSUE TITLE
[BUG]: Host mode does not work on Oracle VPS

### ISSUE THREAD

**Issue by siddharthalodha** [azukaar/Cosmos-Server#193]
### What happened?

I got a popup about migrating network setup. It asked ports 80,443. I didnt change anything. Now I cant seem to access the cosmos server as well docker images created using cosmos earlier.

Docker logs seems fine. I am assuming reverse proxy is broken.

### What should have happened?

It shouldn't have made any changes

### How to reproduce the bug?

Just migrate to the new network setup .

### System details

Using OCI server, Cloudflare dns

**Comment by azukaar** [comment]
You are the third person to say that host mode does not work on Oracle VPS
If one of you three could send me the complete log (in debug mode, see config page) as well as a URL I can use to (try to) access the server I can start investigating :)
thanks for reporting

**Comment by azukaar** [comment]
OCI blocks the port in their default IPTABLE for some reason. Run:

```
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 4242 -j ACCEPT
sudo netfilter-persistent save
```

and you should be good
