### ISSUE TITLE
[BUG]: When you delete volume other volumes became readonly

### ISSUE THREAD

**Issue by TasyDevilsky** [azukaar/Cosmos-Server#194]
### What happened?

It's probably because of the update ability to edit docker-compose file.
When you create any volume for container and after that delete it other volumes become read only.

![image](https://github.com/azukaar/Cosmos-Server/assets/32222739/e5a9b108-6d78-4d7b-af76-f5abdd49a732)

### What should have happened?

When I delete any volume, or bind storage from web interface it shouldn't affect other volumes.

### How to reproduce the bug?

When you choose some container, especially Deluge for me and you try to attach another volume (from webUI Storage option), and after that you delete it, other volumes (config) and every else volume become read only, when you delete this line through WebUI docker-compose editor it will work, but when you repeat scenario (add volume, and after while delete it) it will become read only again.

### Relevant log output

```shell
No relevant output
```

### Other details
It affect also other containers, not only Deluge.
_No response_

### System details

- Cosmos OS: Ubuntu Server 22.04.3 LTS
- Docker version: 25.0.2
- Browser Firefox 122.0.1 (64-bit) Arch linux
- Cosmos version 0.14.3

**Comment by azukaar** [comment]
Fixed in 0.14.4 -- could you retest before I close the ticket please?

**Comment by TasyDevilsky** [comment]
Yeah it's fixed.
PS: For everyone who is affected by this issue, you need to update to 0.14.4 and then add or remove for example "test-volume", and it rewrite the value "ReadOnly" in docker-compose in web interface.
I firstly tried to just delete it from docker-compose, but it didn't work.
