### ISSUE TITLE
[BUG]: RPi5 Won't Connect to AutoCreated MongoDB

### ISSUE THREAD

**Issue by TheBrokenG0d** [azukaar/Cosmos-Server#196]
### What happened?

So I just installed RPI OS and ran the Cosmos Docker run command and made sure I used azukaar/cosmos-server:latest-arm64

When I get to Step 2 to create a DB it pops up downloads and starts the MongoDB and I can see it running in docker but it just sits and spins on the WebUI never allowing to me continue.

### What should have happened?

It should have created the DB and Connected to it, allowing me to continue.

### How to reproduce the bug?

1. Install and Start Cosmo Docker
2. Start New Install
3. Created MongoDB
4. Never Connects and Spins

### System details

Raspberry Pi 5 8GB
Running latest Raspberry Pi OS 64bit

**Comment by azukaar** [comment]
please provide some logs so we can figure this out :)

**Comment by TheBrokenG0d** [comment]
> please provide some logs so we can figure this out :)

What logs would be best, Sorry a little bit of a noob with docker.

**Comment by azukaar** [comment]
`docker logs cosmos-server`

**Comment by TheBrokenG0d** [comment]
`2024/02/15 16:43:39 [INFO] Starting...
2024/02/15 16:43:39 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:43:39 [INFO] Validating config file...
2024/02/15 16:43:39 [INFO] Docker Connected
2024/02/15 16:43:39 [INFO] Bootstrap Container From Tags: a29dc04131042979aaf7f1a48a1447c62f13637c0eede729f7e1b088aee22fda
2024/02/15 16:43:39 [INFO] Done bootstrapping Container From Tags: /cosmos-server
2024/02/15 16:43:39 [INFO] Checking for self updater agent
2024/02/15 16:43:39 [INFO] Docker API version: 1.44
2024/02/15 16:43:39 [INFO] MarketInit: Added market cosmos-cloud
2024/02/15 16:43:39 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:43:39 [INFO] OpenID server initialized
2024/02/15 16:43:39 [INFO] Generating new Auth ED25519 certificate
2024/02/15 16:43:39 [INFO] Config file saved.
2024/02/15 16:43:39 [INFO] Saved new Auth ED25519 certificate
2024/02/15 16:43:39 [INFO] Initialising HTTP(S) Router and all routes
2024/02/15 16:43:39 [INFO] Starting in /app
2024/02/15 16:43:39 [INFO] TLS certificates do not exists or are disabled, starting HTTP server only
2024/02/15 16:43:39 [INFO] Setup: Checking Docker port mapping
2024/02/15 16:43:39 [INFO] Port mapping not changed.
2024/02/15 16:43:39 [INFO] Listening to HTTP on : 0.0.0.0:80
2024/02/15 16:43:53 "GET http://192.168.1.133/ HTTP/1.1" from 192.168.3.2:14349 - 307 46B in 246.091µs
2024/02/15 16:43:53 "GET http://192.168.1.133/cosmos-ui HTTP/1.1" from 192.168.3.2:14349 - 200 630B in 425.995µs
2024/02/15 16:43:54 [INFO] SmartShield: Request received
2024/02/15 16:43:54 [INFO] API: Status
2024/02/15 16:43:54 [INFO] (Re) Connecting to the database...
2024/02/15 16:44:24 [ERROR] Status: Database error : server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: cosmos-mongo-qao:27017, Type: Unknown, Last error: dial tcp: lookup cosmos-mongo-qao on 192.168.1.1:53: no such host }, ] }
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14349 - 200 367B in 30.001078331s
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos-ui/assets/discord_white-ce7ab6fe.svg HTTP/1.1" from 192.168.3.2:14349 - 200 985B in 318.442µs
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos-ui/assets/wallpaper2-15eeb062.jpg HTTP/1.1" from 192.168.3.2:14411 - 200 31481B in 296.85µs
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos/api/me/ HTTP/1.1" from 192.168.3.2:14349 - 200 25B in 128.925µs
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos/api/servapps HTTP/1.1" from 192.168.3.2:14413 - 200 25B in 152.998µs
2024/02/15 16:44:24 "GET http://192.168.1.133/cosmos/api/config HTTP/1.1" from 192.168.3.2:14412 - 200 25B in 166.943µs
2024/02/15 16:44:24 [INFO] SmartShield: Request received
2024/02/15 16:44:24 [INFO] API: Status
2024/02/15 16:44:24 [INFO] SmartShield: Request received
2024/02/15 16:44:24 [INFO] API: Status
2024/02/15 16:44:54 [INFO] (Re) Connecting to the database...
2024/02/15 16:44:54 [INFO] (Re) Connecting to the database...
2024/02/15 16:45:24 [ERROR] Status: Database error : server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: cosmos-mongo-qao:27017, Type: Unknown, Last error: dial tcp: lookup cosmos-mongo-qao on 192.168.1.1:53: no such host }, ] }
2024/02/15 16:45:24 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14414 - 200 367B in 1m0.002082329s
2024/02/15 16:45:24 [ERROR] Status: Database error : server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: cosmos-mongo-qao:27017, Type: Unknown, Last error: dial tcp: lookup cosmos-mongo-qao on 192.168.1.1:53: no such host }, ] }
2024/02/15 16:45:24 [ERROR] Request Timeout. Cancelling. : context deadline exceeded
2024/02/15 16:45:24 [ERROR] HTTP Request returned Error 504 : Gateway Timeout :
2024/02/15 16:45:24 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14413 - 200 431B in 1m0.002660434s
2024/02/15 16:45:25 [INFO] SmartShield: Request received
2024/02/15 16:45:25 [INFO] API: Status
2024/02/15 16:45:55 [INFO] (Re) Connecting to the database...
2024/02/15 16:45:55 [INFO] SmartShield: Request received
2024/02/15 16:45:55 [INFO] NewInstall: Step cleanup
2024/02/15 16:45:55 [INFO] NewInstall: Removing config file
2024/02/15 16:45:55 [INFO] NewInstall: Emptying /config
2024/02/15 16:45:55 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:45:55 [INFO] Config file does not exist. Creating default config file.
2024/02/15 16:45:55 [INFO] Validating config file...
2024/02/15 16:45:55 "POST http://192.168.1.133/cosmos/api/newInstall HTTP/1.1" from 192.168.3.2:5996 - 200 16B in 1.410563ms
2024/02/15 16:46:15 [INFO] SmartShield: Request received
2024/02/15 16:46:15 [INFO] API: Status
2024/02/15 16:46:15 [INFO] (Re) Connecting to the database...
2024/02/15 16:46:15 [ERROR] Status: Database error : error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2024/02/15 16:46:15 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:5996 - 200 367B in 313.59µs
2024/02/15 16:46:25 [ERROR] Status: Database error : server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [] }
2024/02/15 16:46:25 [ERROR] Request Timeout. Cancelling. : context deadline exceeded
2024/02/15 16:46:25 [ERROR] HTTP Request returned Error 504 : Gateway Timeout :
2024/02/15 16:46:25 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14413 - 200 431B in 1m0.002359307s
2024/02/15 16:46:25 [INFO] SmartShield: Request received
2024/02/15 16:46:25 [INFO] API: Status
2024/02/15 16:46:25 [INFO] (Re) Connecting to the database...
2024/02/15 16:46:25 [ERROR] Status: Database error : error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2024/02/15 16:46:25 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:5996 - 200 367B in 264.683µs
2024/02/15 16:46:27 [INFO] SmartShield: Request received
2024/02/15 16:46:27 [INFO] API: Status
2024/02/15 16:46:27 [INFO] (Re) Connecting to the database...
2024/02/15 16:46:27 [ERROR] Status: Database error : error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2024/02/15 16:46:27 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:5996 - 200 367B in 296.776µs
2024/02/15 16:46:29 [INFO] SmartShield: Request received
2024/02/15 16:46:29 [INFO] NewInstall: Step Database
2024/02/15 16:46:29 [INFO] NewInstall: Create DB
2024/02/15 16:46:29 [WARN] ARM64 detected. Using ARM mongo 4.4.18
2024/02/15 16:46:29 [INFO] Starting creation of new service...
2024/02/15 16:46:29 [INFO] Starting creation of new service...

2024/02/15 16:46:29 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:46:29 [INFO] Pulling image arm64v8/mongo:4.4.18
2024/02/15 16:46:29 [INFO] Pulling image arm64v8/mongo:4.4.18

2024/02/15 16:46:30 [INFO] SmartShield: Request received
2024/02/15 16:46:30 [INFO] API: Status
2024/02/15 16:46:30 [INFO] (Re) Connecting to the database...
2024/02/15 16:46:30 [ERROR] Status: Database error : error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2024/02/15 16:46:30 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14413 - 200 367B in 487.034µs
2024/02/15 16:46:30 [INFO] {"status":"Pulling from arm64v8/mongo","id":"4.4.18"}

2024/02/15 16:46:30 [INFO] {"status":"Digest: sha256:a428218c5e7976962879dbeead9997d4d420db360ada18d1a8590e2311a1c640"}

2024/02/15 16:46:30 [INFO] {"status":"Status: Image is up to date for arm64v8/mongo:4.4.18"}

2024/02/15 16:46:30 [INFO] Image arm64v8/mongo:4.4.18 pulled
2024/02/15 16:46:30 [INFO] Image arm64v8/mongo:4.4.18 pulled

2024/02/15 16:46:30 [INFO] Checking service cosmos-mongo-sPh...
2024/02/15 16:46:30 [INFO] Checking service cosmos-mongo-sPh...

2024/02/15 16:46:30 [INFO] Forcing secure cosmos-mongo-sPh...
2024/02/15 16:46:30 [INFO] Forcing secure cosmos-mongo-sPh...

2024/02/15 16:46:30 [INFO] Creating new secure network: cosmos-network-Yjwn7WJsq
2024/02/15 16:46:30 [INFO] Connecting Cosmos to network cosmos-network-Yjwn7WJsq
2024/02/15 16:46:30 [ERROR] Docker Network Connect : Error response from daemon: container sharing network namespace with another container or host cannot be connected to any other network
2024/02/15 16:46:30 [INFO] Created secure network cosmos-network-Yjwn7WJsq
2024/02/15 16:46:30 [INFO] Created secure network cosmos-network-Yjwn7WJsq

2024/02/15 16:46:30 [INFO] Creating container cosmos-mongo-sPh...
2024/02/15 16:46:30 [INFO] Creating container cosmos-mongo-sPh...

2024/02/15 16:46:30 [INFO] CreateService: Connecting to network: cosmos-network-Yjwn7WJsq
2024/02/15 16:46:30 [INFO] Container cosmos-mongo-sPh created
2024/02/15 16:46:30 [INFO] Container cosmos-mongo-sPh created
2024/02/15 16:46:31 [INFO] Container cosmos-mongo-sPh initiated
2024/02/15 16:46:31 [INFO] Container cosmos-mongo-sPh initiated
2024/02/15 16:46:31 [INFO] Config file saved.
2024/02/15 16:46:31 [INFO] CreateService: Operation succeeded. SERVICE STARTED
2024/02/15 16:46:31 [INFO] [OPERATION SUCCEEDED]. SERVICE STARTED

2024/02/15 16:46:31 [INFO] Bootstrap Container From Tags: cbf50929d2258bb15eb8575b0191c237ce3c48f5dc22ac1b70ee35e23e6a8923
2024/02/15 16:46:31 [INFO] Config file saved.
2024/02/15 16:46:31 [INFO] NewInstall: MongoDB created, waiting for it to be ready
2024/02/15 16:46:31 [ERROR] Docker Network Connect EXISTING  : Error response from daemon: container sharing network namespace with another container or host cannot be connected to any other network
2024/02/15 16:46:31 [INFO] /cosmos-mongo-sPh: Checking Force network secured
2024/02/15 16:46:31 [INFO] /cosmos-mongo-sPh: Needs isolating on a secured network
2024/02/15 16:46:31 [INFO] /cosmos-mongo-sPh: Connected to new network
2024/02/15 16:46:31 [INFO] /cosmos-mongo-sPh: Disconnecting from bridge network
2024/02/15 16:46:31 [INFO] Done bootstrapping Container From Tags: /cosmos-mongo-sPh
2024/02/15 16:46:32 [INFO] (Re) Connecting to the database...
2024/02/15 16:46:33 [INFO] SmartShield: Request received
2024/02/15 16:46:33 [INFO] API: Status
2024/02/15 16:46:39 [INFO] Checking for updates for arm64v8/mongo:4.4.18
2024/02/15 16:46:39 [INFO] {"status":"Pulling from arm64v8/mongo","id":"4.4.18"}
2024/02/15 16:46:39 [INFO] {"status":"Digest: sha256:a428218c5e7976962879dbeead9997d4d420db360ada18d1a8590e2311a1c640"}
2024/02/15 16:46:39 [INFO] No updates available for arm64v8/mongo:4.4.18
2024/02/15 16:46:39 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:46:39 [INFO] CheckUpdatesAvailable - Checking local image for change for arm64v8/mongo:4.4.18
2024/02/15 16:46:39 [INFO] CheckUpdatesAvailable - No local updates available for arm64v8/mongo:4.4.18
2024/02/15 16:46:39 [INFO] Checking for updates for azukaar/cosmos-server:latest-arm64
2024/02/15 16:46:40 [INFO] {"status":"Pulling from azukaar/cosmos-server","id":"latest-arm64"}
2024/02/15 16:46:40 [INFO] {"status":"Digest: sha256:36f499b026f4da4e48f5da899de54a3e1f25c89bdc2226be7a9f31e88d0d7794"}
2024/02/15 16:46:40 [INFO] No updates available for azukaar/cosmos-server:latest-arm64
2024/02/15 16:46:40 [INFO] Using config file: /config/cosmos.config.json
2024/02/15 16:46:40 [INFO] CheckUpdatesAvailable - Checking local image for change for azukaar/cosmos-server:latest-arm64
2024/02/15 16:46:40 [INFO] CheckUpdatesAvailable - No local updates available for azukaar/cosmos-server:latest-arm64
2024/02/15 16:47:02 [WARN] DB Not ready yet
2024/02/15 16:47:03 [INFO] (Re) Connecting to the database...
2024/02/15 16:47:33 [ERROR] Status: Database error : server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: cosmos-mongo-sph:27017, Type: Unknown, Last error: dial tcp: lookup cosmos-mongo-sph on 192.168.1.1:53: no such host }, ] }
2024/02/15 16:47:33 [ERROR] Request Timeout. Cancelling. : context deadline exceeded
2024/02/15 16:47:33 [ERROR] HTTP Request returned Error 504 : Gateway Timeout :
2024/02/15 16:47:33 "GET http://192.168.1.133/cosmos/api/status HTTP/1.1" from 192.168.3.2:14413 - 200 431B in 1m0.002798452s
2024/02/15 16:47:33 [INFO] (Re) Connecting to the database...`


I just deleted all containers and tried it again to get clean logs.

**Comment by azukaar** [comment]
You seem to be using a very old version of Cosmos, are you use :latest-arm instead of :latest ? If yes please change to :latest

**Comment by TheBrokenG0d** [comment]
> You seem to be using a very old version of Cosmos, are you use :latest-arm instead of :latest ? If yes please change to :latest

That was my issue, using latest fixed it.  You might want to update your Getting Started Page cause under Other Settings you had this 

"If you are running a Raspberry or another ARM based server, you can use latest-arm64 for an arm architecture image." 

Which lead to my confusion.

**Comment by azukaar** [comment]
Thanks for the heads up, I thought I had gotten rid of it everywhere!
