### ISSUE TITLE
[FEAT]: Translation manager, or localization download function

### ISSUE THREAD

**Issue by miqonee** [azukaar/Cosmos-Server#197]
### Feature Description

Good afternoon, how do you like the idea of ​​adding functionality for downloading localizations, in a key-value format, so that the user has the opportunity to localize into his own language?

As I see it: in the settings there is a localization item, the user can select translation or download this file and translate it into his language, after which he can send it to be added to the main project (then it will appear in the language selection menu), or leave it locally, like this so that each user has the opportunity to set their own language.

**Comment by azukaar** [comment]
- Localisation definitely need to be a thing
- I dont think it needs a download button. Users will be able to see the localization files in this repo
