### ISSUE TITLE
[FEAT]: Clickable link on Proxies

### ISSUE THREAD

**Issue by zarevskaya** [azukaar/Cosmos-Server#2]
### Feature Description

Hi,

It would be handy to be able to click on the url in Proxies to open the page directly. Or to implement a tab with all available links.

![Screenshot 2023-04-08 at 15-12-20 Cosmos](https://user-images.githubusercontent.com/60230221/230723218-03f5d662-84b3-41bf-b6c7-abd79d88ad58.png)

Have a nice day!

**Comment by azukaar** [comment]
Added to v0.1.13
Clicking on the URL will take you there on a new tab
Clicking on the gear icon will take you to the route settings

![image](https://user-images.githubusercontent.com/7872597/230771436-e09cd0b1-aec3-4ae2-b01e-5b8e1a1b41cd.png)

**Comment by zarevskaya** [comment]
Hi,

All work fine now, thank you.
