### ISSUE TITLE
[FEAT]: Things that I see that can be a dealbreaker

### ISSUE THREAD

**Issue by AmadeusGraves** [azukaar/Cosmos-Server#203]
### Feature Description

Hi, first of all, great work, it's an awesome work and project. I have in my machine CasaOS install for over 3 years and your project is very attractive but in my opinion this software needs a list of things that are dealbreakers, please take this as advice, I just want to help you.

### 1
The capability to change the language of the software. It may be weird, but the majority of people will choose the language with they are more comfortable, which in most cases is the first language. If your software have only 1 language, for example English, the people that not are English native speakers will not select your software and will search one that have his language like CasaOS. 

This is a very big problem because if you want that your software become popular, you are cutting a large population of potential consumers of your software and throw it to the direct competence. 

Also, you don't have to do all translation, you can use a third party software that connects with GitHub repo that gives your community the capacity to translate your software, one example is Crowdin. It's free for open-source projects.

Here's the doc to configure Crowdin with github: https://support.crowdin.com/github-integration/
Here's the form to set free an open source project: https://crowdin.com/page/open-source-project-setup-request

### 2
A Console Command, for example CasaOS have the capability of display in his Web UI a terminal, that you can use. 

This is a game changer because if you have one issue in your machine, a lot of people use the terminal to solve the problem. I often use SSH for this kind of thing, but I'm not always in the PC, so I use a smartphone to use this Web UI terminal or a tablet. 

**I see that exists a terminal to access the containers, but no one to access the main OS**. Also, if you combine BTOP with this Web UI Terminal, well, it's a game changer if you want to see very easy your system process, etc...

### 3
A File Manager. This also is a necessity because is very, very easy with this to manipulate inner files of the main OS, with this. For example, you can upload a file, rename a folder...

This File Manager, can also have the functionality of share folders with SMB. This is very good and CasaOS have this, but CasaOS have a poor user management with SMB. Frankly, they don't have user management at all, and this is a weakness that can be used in your favor.

Also, can share files via p2p. Again, poor user management. You have to log in with the same user to pass the files. 

### -----

And that's all I think that can help this project to become more popular. I hope I have not been too abrupt, and best regards.

**Comment by azukaar** [comment]
Thanks for the  feedback, appreciate it
1. I agree, I will implement languages later but I dont want to do it now as it would slow development of feature
2. Also agree, it's a bit tricky thought because as a Docker container you can't really run a host machine terminal. That's  the reason why it's not there yet. Cosmos will be runnable as a daemon later making it more realistic to hve this feature. It is indeed in the roadmap :)
3. Also agree, and also in the roadmap! I have to wrap my head around this one, because there are multiple approach to how to properly do this. The reason why I didn't feel it was high priority is because the Filebrowser app on the Cosmos market works very well anyway. But I will eventually add native file browser

thanks again for the feedback

**Comment by AmadeusGraves** [comment]
Sorry for the late, but I take note, thanks.

**Comment by azukaar** [comment]
@AmadeusGraves  interestingly enough, 2 out of 3 points are now implemented since you posted it :p
/

**Comment by AmadeusGraves** [comment]
I see, you used reversed ssh to conect the main terminal to the SO of the server, right?

Probably i'll start using Cosmos instead of CasaOS because the development of this one has stopped. I think that right now CasaOS is in maintenance mode. 

The problem right now of CasaOS is the development team that is focusing in ZimaOS but ZimaOS is a full SO that i don't want to install because i prefer rely on a stable SO like Debian.

**Comment by azukaar** [comment]
No it is using a websocket and then the Cosmos process has a child bash process and proxy the stdin/stdout
