### ISSUE TITLE
[FEAT]: IPV64 DDNS

### ISSUE THREAD

**Issue by tns772** [azukaar/Cosmos-Server#205]
### Feature Description

The DDNS config doesn’t have IPV64 as server to select when setting up domain for HTTPS.

**Comment by azukaar** [comment]
Cosmos is using the LEGO library and I cannot add providers myself, any request has to go to them

**Comment by tns772** [comment]
The IPV64 is listed as one of the providers it just doesnt show up on COSMOS as a provider

**Comment by tns772** [comment]
https://go-acme.github.io/lego/dns/ipv64/

**Comment by azukaar** [comment]
Ah right I prob just need to update the dependency, I'll do it thanks

**Comment by tns772** [comment]
![COSMOS DDNS Providers](https://github.com/azukaar/Cosmos-Server/assets/58698692/cd6b1649-9d20-4be0-8531-e641fb19e31d)

**Comment by tns772** [comment]
Screenshot from COSMOS DDNS provider. Thank You Azukaar!

**Comment by tns772** [comment]
Azukaar, where you able to update the DDNS options for IPV64

**Comment by azukaar** [comment]
It will be in the next update, which will take 2-3 more weeks
