### ISSUE TITLE
[BUG]: Network Create Error: Error response from daemon: plugin "mcvlan" not found

### ISSUE THREAD

**Issue by TheBrokenG0d** [azukaar/Cosmos-Server#206]
### What happened?

Trying to create a MCVLAN interface on my wlan0 interface and it keeps saying the plugin is not found.

### What should have happened?

It should create the Network.

### How to reproduce the bug?

1. Go to ServApps
2. Click on Networks
3. Click New Network
4. Try to Create MCVLAN

### System details

Raspberry Pi 5 8GB
Running latest Raspberry Pi OS 64bit

**Comment by azukaar** [comment]
Makre sure your docker setup does have the MCVLAN feature
