### ISSUE TITLE
[BUG]: Internal server error whenever I try to expose an app to internet

### ISSUE THREAD

**Issue by likeadragonmaid** [azukaar/Cosmos-Server#213]
### What happened?

Whenever I try to expose an app, let say navidrome, it says Internal server error: lookup navidrome.mydomain.onthewifi.com on 127.0.0.53:53: no such host. I tried it with both self signed cert and also with lets encrypt. My OS is Fedora server and I am using docker as well. I can access the cosmos ui from mydomain.onthewifi.com. My router's dns is set to cloudflare. Also I am using free account from noip.com if that matters.

### What should have happened?

I should be able to access apps via web.

### How to reproduce the bug?

Just install any app and try to expose it to internet,

### System details

- OS: Fedora
- Browser: Any
- Version: 0.14.6

**Comment by azukaar** [comment]
This means that the address was not found in your DNS
 - Might be a simple caching issue, in which case it is safe to igonre
 - Make sure you are not using something like Adguard that can mess up with the DNS
 - Make sure you created either an A entry to navidrome.domain.com in your domain provider, or a wildcard entry to redirect every subdomains to your server

**Comment by likeadragonmaid** [comment]
Thanks for you input! Seems like noip does not let me create A records or wildcards under free account. I've switched to some other dns setup and now it works, once again thanks for helping me narrow down the issue!

**Comment by azukaar** [comment]
どういたしまして、楽しんでください！
