### ISSUE TITLE
[BUG]: Network Create Error: Error response from daemon: plugin "mcvlan" not found

### ISSUE THREAD

**Issue by twjen** [azukaar/Cosmos-Server#218]
### What happened?

<img width="1007" alt="image" src="https://github.com/azukaar/Cosmos-Server/assets/7020714/e49a2851-f046-44c3-9a57-9158f4fb97ef">

### What should have happened?

When create new network use driver mcvlan will show this error message.

I think it should name macvlan.
Maybe it loss a char is 'a'.

### How to reproduce the bug?

1. Go to 'ServApp'
2. Click on 'Networks'
3. Click on 'New Network'
5. Click on 'driver'
6. Scroll down to 'MCVLAN'
7. Click on 'Create'
8. See error

### System details

- OS: [e.g. iOS] windows 11 23h2
- Browser [e.g. chrome, safari] edge
- Version [e.g. 22] 122.0.2365.92
- Cosmos Version: 0.14.6

**Comment by azukaar** [comment]
fixed in 0.15
