### ISSUE TITLE
[FEAT]: ZeroSSL Support

### ISSUE THREAD

**Issue by Artermyss** [azukaar/Cosmos-Server#22]
### Feature Description

Cosmos looks brilliant and I am looking forward to trying it with a view of implementing it permanently on my server, however I wanted to see whether there could be support implemented for ZeroSSL certificates as an alternative for LetsEncrypt. 

If you’re using acme.sh, it should be possible to plug the EAB credentials in and use ZeroSSL quite easily. :)

Thanks!

**Comment by azukaar** [comment]
Cosmos is using an embedded Certbot which only supports LE
any reasons you prefer not to use it?

**Comment by RedKage** [comment]
I'm also looking for a ZeroSSL implementation. I started to play with Cosmos and I plan to migrate some of my servers to it.
Though, I'm currently using acme.sh as well with ZeroSSL to generate ECDSA SSL certs.
Using acme.sh would enable the users to use different signatures and cyphers.

But
I think the real need may not be to implement acme.sh, but rather to have a way for us to use our "existing certs" and to import them in cosmos automatically. Not just
That way people could use whatever tools they like to generate certs.

I would keep using acme.sh with my cron job to generate a cert. But I need a way after the cert has been generated to import it to Cosmos.
Maybe through some API for instance.
Or maybe by supplying filesystem paths to the public and private cert files. Which Cosmos would import upon change. Maybe it's actually simpler.

I haven't looked deeper, I suspect it would currently be possible to access the Cosmos database and to inject the newly created certs directly maybe, but this feels hackish.

For now Let's Encrypt works fine for my use case. It's not a big deal.

**Comment by azukaar** [comment]
@RedKage If you have a cron job to generate a cert, you could use the same CRON job to manually edit the config file (in /var/lib/cosmos/) and restart Cosmos. No need to edit the DB. This way you could effectively import  your cert from whatever tool you are using to generate them

**Comment by RedKage** [comment]
> @RedKage If you have a cron job to generate a cert, you could use the same CRON job to manually edit the config file (in /var/lib/cosmos/) and restart Cosmos. No need to edit the DB. This way you could effectively import your cert from whatever tool you are using to generate them

It works great!

Here is a script I made

```
#!/bin/bash
scriptDir=$(dirname $0)
pushd "$scriptDir"

public="$(cat /cert.cer)"
private="$(cat /cert.key)"
expiry="$(openssl x509 -noout -enddate -in /cert.cer)"

# Remove "notAfter=" from the expiry output
expiry=${expiry//notAfter=/}

# Convert to ISO date
expiry=$(date -u -Iseconds --date "$expiry")

# Convert to milliseconds
expiry=${expiry/+00:00/.000000000Z}

# Update cosmos config
cat /var/lib/cosmos/cosmos.config.json| jq --arg public "$public" --arg private "$private" --arg expiry "$expiry" \
        '.HTTPConfig.TLSCert = $public | .HTTPConfig.TLSKey = $private | .HTTPConfig.TLSValidUntil = $expiry' > /var/lib/cosmos/cosmos.config.json

popd
```

**Comment by azukaar** [comment]
Great job make sure you set HTTPS mode to "Provided" too so Cosmos does not try to renew it itself
