### ISSUE TITLE
[BUG]: ACME Challenge Propagation Timeout Issue

### ISSUE THREAD

**Issue by b1nary-b0b** [azukaar/Cosmos-Server#220]
### What happened?

Hey Guys, 

I get this message: 
error: one or more domains had a problem: [domain.it] propagation: time limit exceeded: last error: NS second-dns.netcup.net. returned NXDOMAIN for _acme-challenge.domain.it. [video.domain.it] propagation: time limit exceeded: last error: NS second-dns.netcup.net. returned NXDOMAIN for _acme-challenge.video.domain.it. 
(random domain names)

I want to use wildcard cert with my provider Netcup. 
I have used the required API-configuration and I can see the respective TXT entry being created successfully.
When using non-wildcard i am able to obtain a certificate for at least the base domain, other subdomains still fail.

My suspicion is that my DNS provider has a propagation time, that exceeds the timeout. Anyone any idea how to circumvent this issue?

Thanks a ton! 🙂

### What should have happened?

Wildcard cert has been created. 

### How to reproduce the bug?

I have used the required API-configuration and I can see the respective TXT entry being created successfully.
When using non-wildcard i am able to obtain a certificate for at least the base domain, other subdomains still fail.

### Relevant log output

```shell
error: one or more domains had a problem: [domain.it] propagation: time limit exceeded: last error: NS second-dns.netcup.net. returned NXDOMAIN for _acme-challenge.domain.it. [video.domain.it] propagation: time limit exceeded: last error: NS second-dns.netcup.net. returned NXDOMAIN for _acme-challenge.video.domain.it.
```

### System details

- OS: host is running Ubuntu 22.04LTS

**Comment by azukaar** [comment]
You can extend the timeout, depends on your provider, see the doc linked in the setting page when choosing provider
(you have to set the env var on the cosmos container)

**Comment by b1nary-b0b** [comment]
Thanks a ton, that was exactly the piece of information missing - where to set this timeout. :) Worked perfectly!
