### ISSUE TITLE
[BUG]: When deleting a service, the homepage is not up do date

### ISSUE THREAD

**Issue by null-except** [azukaar/Cosmos-Server#223]
### What happened?

When I deleted the Code-Server container via the Cosmos UI, in the homepage the logo for Code-Server is still visible. 

Same when in the CLI I prune some old images and some stopped container. 

### What should have happened?

It should have been deleted. It worked for some other apps (Immich for instance). 

### How to reproduce the bug?

1. Go to market, install Code Server. 
2. Go to ServerApps.
3. Kill and delete the Code Server container. 
4. Go to homepage, Code Server is still there. 

### System details

- OS: Ubuntu 20.04
- Browser: Thorium
- Version: 0.15.1

**Comment by null-except** [comment]
Deleting the URL in the Url scetion will solve the problem. 

Also, when deleting an application, some urls are not deleted. For example, for Nextcloud, only one out of three was successfully automatically deleted.

**Comment by azukaar** [comment]
As you found out, the homepage is using the URLs and not the containers to populate itself
did you install the code server via  the market? If the URL was not marked for deletion when you deleted the container it might be because you were not using the SERVAPP mode in the URL itself (in case you built it yourself)

**Comment by null-except** [comment]
Yes I used the market for Immich and code server (default source). The url was marked as deleted with a checkmark when I deleted the container.

**Comment by azukaar** [comment]
Hmm that is weird I cannot reproduce it, could it be you had multiple tabs opened and you re-saved the config file with the URLs in them for example ?

**Comment by null-except** [comment]
Maybe something was wrong with my config, I'm now on 0.15.3 and everything seems fine! Sorry for the bother
