### ISSUE TITLE
[BUG]: UI Accessibility Issue and Migration Error with Docker Desktop Installed.

### ISSUE THREAD

**Issue by armelhbobdad** [azukaar/Cosmos-Server#229]
### What happened?

- After installing Docker Desktop on the local machine and following the documentation for a fresh installation, attempting to run cosmos with `docker run --network host ....` results in an inability to access the UI.
- Despite specifying ports as instructed for Windows or Mac, the UI only becomes accessible. However, after the installation, a warning message prompts to migrate to network host again.
- Accepting the migration action leads to encountering the same problem with UI accessibility post-migration.

### What should have happened?

- Upon running cosmos with `docker run --network host ....`, the UI should have been accessible without any issues.
- Following the migration to network host, the UI should remain accessible without any hindrances.

### How to reproduce the bug?

1. Install Docker Desktop on the local machine.
2. Follow the documentation for a fresh installation of cosmos.
3. Run cosmos with `docker run --network host ....`
4. Observe the inability to access the UI.
5. Specify ports as mentioned for Windows or Mac, which enables UI accessibility but triggers a warning message to migrate to network host.
6. Accept the migration action.
7. Notice that the problem persists with UI accessibility post-migration.

### System details

- Debian 12
- Chrome Version 123.0.6312.86 (Official Build) (64-bit)

**Comment by azukaar** [comment]
dont accept the migration, as the migration pop up says, it will not work on windows/mac. You can disable the popup in the config file

**Comment by armelhbobdad** [comment]
My OS is Linux, Debian 12 with Docker Desktop. Please review my issue.

**Comment by azukaar** [comment]
Sorry missed that detail
Docker Desktop won't work either has it is not full docker (it uses VMs instead of the docker virtualization)
thanks

**Comment by armelhbobdad** [comment]
I updated the issue title by adding "Debian" to prevent duplication by others. Thank you.
