### ISSUE TITLE
[BUG]: Password not strong enough

### ISSUE THREAD

**Issue by Re4mstr** [azukaar/Cosmos-Server#23]
### What happened?

Using the password "Th|sSh0u1dSuff|ce" does not meet the requirements, even though the "strength indicator" shows "Strong" and meets all the given requirements.

### What should have happened?

The password should be accepted and be valid.

### How to reproduce the bug?

1. Run docker install command as instructed.
2. Go to install wizard URL
3. On Admin Account Step (4/4):
4. Use the following password: "Th|sSh0u1dSuff|ce"

### System details

- OS: Alpine LXC, Proxmox
- Browser: Firefox
- Version: Latest as of issue
- Screenshot: 
![image](https://github.com/azukaar/Cosmos-Server/assets/15211713/795fed70-3d1c-4c7c-b3a2-036ecdff1d48)

**Comment by azukaar** [comment]
Thanks for the report, the validator indeed checks for !@#$%^&* only, I will add more to it in  the next release

**Comment by azukaar** [comment]
Fixed in 0.7.6
