### ISSUE TITLE
[BUG]: Update Nextcloud 28.0.4 from 28.0.3

### ISSUE THREAD

**Issue by McFlyPartages** [azukaar/Cosmos-Server#230]
### What happened?

Nextcloud update not working due to `config.php` settings

### What should have happened?

I can't connect to the Nextcloud instance since I updated it. It says that the `config.php` file doesn't allow updating via the UI.

In `ServApps` it tells me that an update is available, but that I need to go into the stack details to update.

The automatic update button is not checked, whereas in `View Stack` it is.

![Capture d’écran du 2024-04-02 10-50-05](https://github.com/azukaar/Cosmos-Server/assets/44530252/b7d2068e-7578-4bb1-a5e4-14c58d141a19)

*For information, installing a second instance tells me the same thing, even though it's version 28.0.4, but once installed I can connect to it.

Here's the error when I try to connect:

```
Update required
Please use command-line updating, as updating via the browser is disabled in your config.php file.

For help, please read the documentation. 
```
![Capture d’écran du 2024-04-02 10-57-33](https://github.com/azukaar/Cosmos-Server/assets/44530252/a2bf0750-d245-4a6d-a27f-3c2c9bdfb69c)

Got an idea? Is this a bug or have I missed a procedure?

Thanks in advance

### How to reproduce the bug?

1. force install old version
2. attemps cosmos auto update
3. connect to your instance

### Relevant log output

```shell
Error Only
Limit
2024-04-02 08:07:26
Configuring Redis as session handler
2024-04-02 08:07:26
Initializing nextcloud 28.0.4.1 ...
2024-04-02 08:07:39
ProcessfProcessdProcessgProcessdProcessfProcess Process Process Process Process Process Process Process ProcessProcess Process Process Process Process Process Process Process Process Process Process Process ProcessProcess^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(518) [generator=3.2.7]
2024-04-02 08:07:39
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(713) [sender=3.2.7]
2024-04-02 08:07:40
Configuring Redis as session handler
2024-04-02 08:07:40
Initializing nextcloud 28.0.4.1 ...
2024-04-02 08:08:01
ProcessbProcessoProcessnProcessoProcess Process Process Process New nextcloud instance
2024-04-02 08:08:01
Initializing finished
2024-04-02 08:08:01
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
2024-04-02 08:08:01
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.4. Set the 'ServerName' directive globally to suppress this message
2024-04-02 08:08:01
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.4. Set the 'ServerName' directive globally to suppress this message
2024-04-02 08:08:02
[Tue Apr 02 08:08:02.328556 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.17 configured -- resuming normal operations
2024-04-02 08:08:02
[Tue Apr 02 08:08:02.328688 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
2024-04-02 08:12:43
ProcessiProcessjProcessuProcessiProcess 172.19.0.1 - - [02/Apr/2024:08:12:42 +0000] "HEAD / HTTP/1.1" 503 1636 "https://ndd.fr/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
```
```


### Other details

_No response_

### System details

- OS: VM Debian 12.5
- Browser [Firefox and Brave sur]
- Version [last]

**Comment by azukaar** [comment]
Hi in the future, would you mind opening this kind of tickets on the appstore instead of the main app as this is a NC issue not a Cosmos issue ? Thanks
https://github.com/azukaar/cosmos-servapps-official

As per what to do: NC being broken (again)..

Installing a new instance will work: you simply installed an instance over an existing folder, causing the folder to already be on the wrong version (NC's folder is a bind not a volume for technical blockers).

As to how to update your instance properly, chek the NC doc: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html

Esp. the part abotu the updater: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html

You can either enable the web one, or do it via CLI

PS: ` The automatic update button is not checked, whereas in View Stack it is.` > The update button is on only for the main container so the stack itself is not "auto-updating"

**Comment by McFlyPartages** [comment]
> Hi in the future, would you mind opening this kind of tickets on the appstore instead of the main app as this is a NC issue not a Cosmos issue ? Thanks https://github.com/azukaar/cosmos-servapps-official
> 
> As per what to do: NC being broken (again)..
> 
> Installing a new instance will work: you simply installed an instance over an existing folder, causing the folder to already be on the wrong version (NC's folder is a bind not a volume for technical blockers).
> 
> As to how to update your instance properly, chek the NC doc: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html
> 
> Esp. the part abotu the updater: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html
> 
> You can either enable the web one, or do it via CLI
> 
> PS: ` The automatic update button is not checked, whereas in View Stack it is.` > The update button is on only for the main container so the stack itself is not "auto-updating"

Thanks for explain and sorry for the bad repo.
