### ISSUE TITLE
[BUG]: Create ServApp Port Mixup in Compose

### ISSUE THREAD

**Issue by mandopatriot** [azukaar/Cosmos-Server#232]
### What happened?

When creating a ServApp and adding ports to expose, host port and container port are swapped in the compose file. 

EXAMPLE - I put 8080 in host port and 80 in container port, because my host already has 80 in use but the container uses 80. The docker compose generated puts 80 for the host and 8080 for container, like "80:8080/tcp".

### What should have happened?

I put 8080 in host port and 80 in container port, because my host already has 80 in use but the container uses 80. In the compose file, it should be "8080:80/tcp".

### How to reproduce the bug?

1. Go to ServApps.
2. Click Start ServApp
3. Enter any relevant info and continue to Network tab.
4. Add a port to expose.
5. Continue to Review & Start tab and view compose file.

### Relevant log output

```shell
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
```

### System details

- Comos: 0.15.3
- OS: Windows 11
- Browser: Firefox
- Version: 124.0.1 64-bit

**Comment by azukaar** [comment]
Fixed in 0.15.4
