### ISSUE TITLE
[BUG]: Installation window  field "Devices" is ignored

### ISSUE THREAD

**Issue by TasyDevilsky** [azukaar/Cosmos-Server#237]
### What happened?

When you try to install something from Market, for example, Jellyfin, you can choose a device to passthrough to the container, but in the next window it's ignored, also the created container is affected and you need to add Device again after creation of container.
![Screenshot from 2024-04-03 07-44-41](https://github.com/azukaar/Cosmos-Server/assets/32222739/fe792e6e-100a-4cb3-bf97-2d80957f287b)

### What should have happened?

It should be in the creation of service, and also contained when the container is successfully created

![Screenshot from 2024-04-03 07-43-11](https://github.com/azukaar/Cosmos-Server/assets/32222739/1e9d76f0-bae2-4d7e-91d1-101be1de556f)

### How to reproduce the bug?

1. Go to Market
2. Click on install Jellyfin
3. Scroll down to Devices
4. Try to add some device for example `/dev/dri/renderD128`
5. It will disappear in the next window.
6. See error

### System details

Server side:
- OS: Cosmos in LXC container
- Version [`0.15.3`]

User side:
- OS: [Arch]
- Browser [Firefox]
- Version [`124.0.1`]

**Comment by mandopatriot** [comment]
So that's why my Plex didn't passthrough my iGPU.. nice find!

**Comment by azukaar** [comment]
Fixed in 0.15.4
