### ISSUE TITLE
Network mode change update lost access admin portal

### ISSUE THREAD

**Issue by dhumphrey7** [azukaar/Cosmos-Server#241]
### What happened?

Updated the network mode to host and now I can't connect to cosmos via domain or IP.  I looked through the docker logs via CLI but don't see any errors.   Containers can be accessed via IP:port still.

### What should have happened?

Should be able to still access the admin panel.

### Other details

I don't know what else to provide.  

### System details

- OS Ubuntu 22.04 ARM64
- Browser Firefox

**Comment by dhumphrey7** [comment]
I was able to fix it by stopping and rm'ing cosmos-server and and running it with the ports instead of host.  I would still like to migrate up to the host network but not sure exactly went wrong the first time.

**Comment by azukaar** [comment]
It's an issue with your system firewall, your ports are not opened on your server (either UFW or iptables)

**Comment by surajmandalcell** [comment]
If its an issue with firewall it would've not worked with bridged mode too, but it does when used with -p 80 & 443 @azukaar.

**Comment by azukaar** [comment]
@surajmandalcell that is not true, Docker bypasses firewalls when using the bridge mode by altering your IPTABLE. That is why many people had issue while migrating out of it

**Comment by surajmandalcell** [comment]
@azukaar damn I did not know that, thank you.
