### ISSUE TITLE
[BUG]: Error while starting container: mkdir /var/lib/cosmos: read-only file system

### ISSUE THREAD

**Issue by alelom** [azukaar/Cosmos-Server#252]
### What happened?

Ubuntu server 24. When running the one-liner installer:
```
docker run -d --network host  --privileged --name cosmos-server -h cosmos-server --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /:/mnt/host -v /var/lib/cosmos:/config azukaar/cosmos-server:latest
```

I get:

```
docker: Error response from daemon: error while creating mount source path '/var/lib/cosmos': mkdir /var/lib/cosmos: read-only file system.
```

The container is started, but I cannot connect to Cosmos-cloud.

Some users report elsewhere that this can be [worked around using docker compose](https://www.reddit.com/r/CosmosServer/comments/1c12hc8/error_while_starting_container_mkdir_varlibcosmos/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). I can confirm that the workaround works for me too. It consists in changing the `config` filepath in the yaml file.

I still wonder why the workaround is required and why the one-liner fails.

### What should have happened?

The error should not appear.

### How to reproduce the bug?

1. Run the docker one-liner install [as instructed by the Get Started](https://cosmos-cloud.io/doc/1%20index/)
2. The error appears

### System details

- OS: Ubuntu 24.04 LTS
- Version latest

**Comment by azukaar** [comment]
are you 
 - using rootless docker
 - using docker desktop

If yes then that might be the root of the issue, either way the one liner itself obviously work in a "normal" environment, that would be insane otherwise, You might want to check:
 - if the folder /var/lib (system folder) is actually set to read-only for some reason
 - if you have a permissions issue 
 - if your disk has space remaining 

If you can't pin the issue, try to install into a different directory

**Comment by alelom** [comment]
Thank you, I realised later that my question wasn't well researched. Apologies and thanks for the explanation.

**Comment by alelom** [comment]
I just wanted to report what was the actual issue.

The issue is with the Docker installation that comes shipped with Ubuntu. You need to uninstall it and then follow the official Docker installation instructions. See this: https://stackoverflow.com/questions/52526219/docker-mkdir-read-only-file-system#comment106888743_52566470

After doing that, I was able to install Cosmos without trouble using the single liner. 

I came back to this because I also was experiencing other issues with Docker on my Ubuntu server, I suspect the source was the same.

**Comment by azukaar** [comment]
You mean there was a pre-installed Docker on your ubuntu install?? Which distro is it exactly? Ubuntu server or desktop?
Was it Docker Desktop (with the UI) ?

**Comment by alelom** [comment]
> Which distro is it exactly? Ubuntu server or desktop?

Ubuntu Server 24.04 LTS (no GUI) as stated in the issue.

> You mean there was a pre-installed Docker on your ubuntu install?? 

Yes, if so selected during the Ubuntu install:

![image](https://github.com/azukaar/Cosmos-Server/assets/6352844/99a50835-b473-4a16-95d7-ae871aedc423)

This option must be toggled off, or Docker needs to be re-installed [as explained in my previous post](https://github.com/azukaar/Cosmos-Server/issues/252#issuecomment-2143059988), where I also left a Reddit post link showing that it can indeed happen to other people.

**Comment by azukaar** [comment]
Good to know thanks
