### ISSUE TITLE
[BUG]: Loop check for the presence of docker istalled

### ISSUE THREAD

**Issue by CavaleriOmar** [azukaar/Cosmos-Server#259]
### What happened?

I am attempting to install cosmos-server on a pc running almalinux 9 (preferred over ubuntu server for a long list of reasons) but, no matter how carefully I removed podman and installed docker, the installation procedure from webui stops at the first step, getting stuck in a loop on checking for the presence of docker.

Not knowing what might be relevant as a log, I put them all.

### What should have happened?

Running the wizard at the /newinstall page, at step 1 it should recognize docker installed and continue, instead of this loop (no matter how long you wait, even hours, it stays put)

![Schermata_20240526_132422](https://github.com/azukaar/Cosmos-Server/assets/54171779/ea542981-d4a2-4140-89c0-3b2086207da7)

### How to reproduce the bug?

1. Go to 'localhost/cosmos-ui/newinstall'
2. Click on 'start'

### Relevant log output

```shell
2024/05/26 11:22:13 [INFO] ------------------------------------------
2024/05/26 11:22:13 [DEBUG] checkVersion{
  "version": "0.15.7",
  "buildDate": "Thu Apr 25 15:46:14 UTC 2024",
  "built from": "ip-10-0-23-1"
}

2024/05/26 11:22:13 [INFO] Starting Cosmos-Server version 0.15.7
2024/05/26 11:22:13 [INFO] ------------------------------------------
2024/05/26 11:22:13 [INFO] Using config file: /config/cosmos.config.json
2024/05/26 11:22:13 [INFO] Config file does not exist. Creating default config file.
2024/05/26 11:22:13 [INFO] Validating config file...
2024/05/26 11:22:13 [INFO] Docker Connected
2024/05/26 11:22:13 [INFO] Cosmos IsHostNetwork: true
2024/05/26 11:22:13 [INFO] Checking for self updater agent
2024/05/26 11:22:13 [INFO] Docker API version: 1.45
2024/05/26 11:22:13 [INFO] Generating new Auth ED25519 certificate
2024/05/26 11:22:13 [INFO] Config file saved.
2024/05/26 11:22:13 [INFO] Saved new Auth ED25519 certificate
2024/05/26 11:22:13 [INFO] Initialising HTTP(S) Router and all routes
2024/05/26 11:22:13 [INFO] Starting in /app
2024/05/26 11:22:13 [INFO] TLS certificates do not exists or are disabled, starting HTTP server only
2024/05/26 11:22:13 [INFO] Network: Initializing internal TCP proxy
2024/05/26 11:22:13 [INFO] Listening to HTTP on : 0.0.0.0:80
2024/05/26 11:25:13 [INFO] Checking for updates for azukaar/cosmos-server:latest
2024/05/26 11:25:15 [INFO] {"status":"Pulling from azukaar/cosmos-server","id":"latest"}
2024/05/26 11:25:15 [INFO] {"status":"Digest: sha256:db2b21c7f591f80f1913af6c8815acd710abb13dfda0415217264523949bc0d3"}
2024/05/26 11:25:15 [INFO] No updates available for azukaar/cosmos-server:latest
2024/05/26 11:25:15 [INFO] Using config file: /config/cosmos.config.json
2024/05/26 11:25:15 [INFO] CheckUpdatesAvailable - Checking local image for change for azukaar/cosmos-server:latest
2024/05/26 11:25:15 [INFO] CheckUpdatesAvailable - No local updates available for azukaar/cosmos-server:latest
```

### System details

AlmaLinux 9.4

**Comment by azukaar** [comment]
So the Docker connection seems fine according to the log, so it is probably the server being completely unreachable.
Try in incognito, and make sure the requests in the browser actually reach the server

**Comment by CavaleriOmar** [comment]
In incognito, "connection failed"

**Comment by azukaar** [comment]
You mean the browser error? 
Can you show the full error please?
