### ISSUE TITLE
[FEAT]: Testing SMTP option

### ISSUE THREAD

**Issue by mzb2xeo** [azukaar/Cosmos-Server#260]
### Feature Description

Testing the smtp config required me to scroll to the end of the page to save, then go to users, create new user, then send a invite, and then send password reset emails. 

Request the following be added within the "Emails - SMTP" section:
1. An additional save button 
2. A box to enter a test email address
3. A send/test button to execute.

**Comment by azukaar** [comment]
Duplicate of #76
