### ISSUE TITLE
[FEAT]: Cosmos-Server Jabber/XMPP Server on Market?

### ISSUE THREAD

**Issue by Somnius** [azukaar/Cosmos-Server#263]
### Feature Description

Haven't seen a decent jabber/xmpp implementation on the market of latest cosmos-server. 

It can be installed e.g. ejabberd thru portainer or docker cli command, 
but, it could have been fun to have one on the market 😊

**Comment by azukaar** [comment]
Please open suggestion for apps in the market's own repo :) 
https://github.com/azukaar/cosmos-servapps-official
