### ISSUE TITLE
[FEAT]: Its possible to add Mirotalk

### ISSUE THREAD

**Issue by alexonbstudio** [azukaar/Cosmos-Server#266]
### Feature Description

https://github.com/miroslavpejic85/mirotalk 

its possible to create same like google meet is very interesting 

ps: why you kick me i propose to add to this apps for cosmos cloud

**Comment by azukaar** [comment]
You posted multiple links one after another I thought it was spams sorry - 
I'll close this ticket, please open app suggestion tickets on https://github.com/azukaar/cosmos-servapps-official
