### ISSUE TITLE
[BUG]: SCRAM-SHA-1 Authentication failed when using own DB credentials

### ISSUE THREAD

**Issue by psybernoid** [azukaar/Cosmos-Server#27]
### What happened?

When launching install wizard and selecting supply my own credentials, the web GUI seemingly accepts it.
![image](https://github.com/azukaar/Cosmos-Server/assets/600235/7b0cd329-69c6-450c-b866-76dead4c35af)

However, progress is not made, docker logs show:
`[ERROR] Status: Database error : connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.`

### What should have happened?

Presumably, when supplying database credentials, the wizard should skip this step and connect?

### How to reproduce the bug?

Sample docker-compose file. Should be able to reproduce from this.

version: '3.3'
services:
  cosmos-server:
    image: 'azukaar/cosmos-server:latest'
    container_name: cosmos-server
    restart: unless-stopped
    depends_on:
      - cosmo-mongo
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cosmos
    environment:
      - COSMOS_HOSTNAME:'192.168.99.140'
      - COSMOS_MONGODB:'mongodb://cosmo:b9TYJc.gef69f*!dsFrewdfsf5432DFDFs@cosmo-mongo'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/:/mnt/host'
      - '/docker/cosmos:/config'

  cosmo-mongo:
    image: mongo:latest
    container_name: cosmo-mongo
    restart: unless-stopped
    networks:
      - cosmos
    environment:
      MONGODB_INITDB_ROOT_USERNAME: cosmo
      MONGODB_INITDB_ROOT_PASSWORD: b9TYJc.gef69f*!dsFrewdfsf5432DFDFs
    volumes:
      - '/docker/mongo/db:/data/db'
      - '/docker/mongo/configdb:/data/configdb'

networks:
  cosmos:
    name: cosmos-db
    external: false

### Relevant log output

```shell
[ERROR] Status: Database error : connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
```

### System details

Alpine Linux 3.17

**Comment by azukaar** [comment]
This is just mongo complaining about "Authentication Failed"
aka. your password is wrong
that can have two reasons:
 - one of the special character in  the password is breaking mongo
 - you mis-setup Mongo DB and this is the wrong password (that can happen if you already have a password set and then change it in the env, it will still use the old password and not update it for example)
 
 1. try to remove special char from the password
 2. make sure you wipe Mongo properly (including any volumes / bind mounted) and recreate it from scratch

**Comment by psybernoid** [comment]
Re-creating from scratch and changed the password to something simple - Abcd1234.

Still the same error.

**Comment by azukaar** [comment]
Try removing `name: cosmos-db` in your network?

**Comment by psybernoid** [comment]
Right. Got it, the issue was with the environment variables in the mongo container. I was using the docker-compose posted here: https://github.com/azukaar/Cosmos-Server/issues/11#issuecomment-1547482207 as an initial guide.

Below is a working config template:

version: '3.3'
services:
  cosmos-server:
    image: 'azukaar/cosmos-server:latest'
    container_name: cosmos-server
    restart: unless-stopped
    depends_on:
      - cosmo-mongo
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cosmos
    environment:
      - COSMOS_HOSTNAME:'192.168.99.140'
      - COSMOS_MONGODB:'mongodb://cosmo:QAZWSX12345@cosmo-mongo'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/:/mnt/host'
      - '/docker/cosmos:/config'

  cosmo-mongo:
    image: mongo:latest
    container_name: cosmo-mongo
    restart: unless-stopped
    networks:
      - cosmos
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: cosmo
      MONGO_INITDB_ROOT_PASSWORD: QAZWSX12345
    volumes:
      - '/docker/mongo/db:/data/db'
      - '/docker/mongo/configdb:/data/configdb'

networks:
  cosmos:
    external: false

**Comment by azukaar** [comment]
Glad you worked it out!
