### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by windowsagent** [azukaar/Cosmos-Server#276]
### What happened?

Whenever I try opening syncthing, forwarded using a servapp url (prefix), I get all sort of errors (as it's trying to access locations like /syncthing/app.js, but it fails). I'm not sure how to forward this application through a prefix, as I can't use subdomains.

### What should have happened?

Syncthing container forwarded such that a client requests "/syncthing/app.js" and it gets the needed file from the syncthing container.

### Relevant log output

```shell
{
  "id": "668df3fae975bf8b68d97184",
  "label": "Proxy Response syncthing error",
  "application": "Cosmos",
  "eventId": "cosmos.proxy.response.syncthing.error",
  "date": "2024-07-10T02:37:43.269Z",
  "level": "warning",
  "data": {
    "bytes": 19,
    "clientID": "177.249.162.151",
    "method": "GET",
    "route": "syncthing",
    "status": 404,
    "time": 0.000726043,
    "url": "/syncthing/app.js"
  },
  "object": "route@syncthing"
}
```

### System details

- OS: Ubuntu
- Browser Firefox
- Version 127

**Comment by azukaar** [comment]
Most apps dont support sub-path, if they do you need to add it as a config in the app itself
