### ISSUE TITLE
[BUG]: PHP FastCGI support?

### ISSUE THREAD

**Issue by Starstrike** [azukaar/Cosmos-Server#277]
### What happened?

Currently I use Caddy to connect to a FastCGI server to handle connections from a static page to MySQL. I don't see an option to configure that here in Cosmos. Is there PHP FastCGI support that I'm just not seeing?

### What should have happened?

Should have seen an option to connect to fastcgi to handle the php files that allow my static site to connect to mysql

### How to reproduce the bug?

1. Go to create a URL
2. Make it a Static Page
3. See there are no options to connect to a fastcgi container to handle php files

### System details

- OS: Windows 10 using WSL2
- Browser: Edge
- Version: 126

**Comment by azukaar** [comment]
I do not think it should be implemented in Cosmos itself, instead I would suggest using a container like this one: https://github.com/KTOmega/docker-nginx-fastcgi

That you can then pick up using Cosmos' proxy
