### ISSUE TITLE
[FEAT]: Gzip support for static routes

### ISSUE THREAD

**Issue by brezinajn** [azukaar/Cosmos-Server#282]
### Feature Description

I have file something.json.gz and I'd like to be able to serve it statically from /something.json with `Content-Encoding:
gzip`.
Current behavior: /something.json route returns 404 since there is no something.json file present

Alternative solutions: Use nginx ☹️

**Comment by azukaar** [comment]
The header is not present but AFAIK the zipping is still happening, you can see it when you use speedtest tools for example
