### ISSUE TITLE
[FEAT]: Peertube container

### ISSUE THREAD

**Issue by audricd** [azukaar/Cosmos-Server#283]
### Feature Description

Good morning,

As a user (admin), I would like to be able to set up a new application, Peertube, from the market directly
https://github.com/Chocobozzz/PeerTube

Thank you very much!

Regards,

**Comment by azukaar** [comment]
thanks for the ticket, please open app suggestions ticket on the market itsefl https://github.com/azukaar/cosmos-servapps-official
