### ISSUE TITLE
[BUG]: Unable to edit users EXCEPT for their email addresses

### ISSUE THREAD

**Issue by audricd** [azukaar/Cosmos-Server#286]
### What happened?

When I click on a User, I can only edit its email address

### What should have happened?

When I click on a user, I should be able to change his name; change his group
![image](https://github.com/user-attachments/assets/85a6bca4-644a-4595-9ca1-b290a5f95000)
It doesnt matter where I click on the User, the only pop up that appears, is the one on the picture. 

### How to reproduce the bug?

1. Login to your Cosmos Server
2. Click on "Users" on the left pane (cosmos-ui/config-users)
3. Click wherever on the desired User

### System details

- OS: Debian 12 (host) Docker stable
- Browser: Firefox 129 Developer Edition

**Comment by azukaar** [comment]
This is the intended behaviour. If you want to change their name you have to create a new user instead

**Comment by audricd** [comment]
Thanks!
