### ISSUE TITLE
[FEAT]: Add posibility to use another SSO solution like Keycloak

### ISSUE THREAD

**Issue by schmierlappe** [azukaar/Cosmos-Server#287]
### Feature Description

Is it possible to use for example Keycloak authentication on running containers in Cosmos-UI. Can't find any documentation only how to use the internal one from Cosmos-UI.

Example:

Keycloak Container running
Uptime-Kuma Container running with disabled authentication and there I want to use Keycloak SSO

on Apps (Portainer, Grafana) where I can setup OAUTH  within the App it is running fine but not all have OAuth implemented.

Maybe it is possible to do with labels where the Reverse Proxy point to the Auth URL or do I need an oauth proxy running in Cosmos-UI?

**Comment by azukaar** [comment]
#133
