### ISSUE TITLE
[BUG]: Frame overflow

### ISSUE THREAD

**Issue by zarevskaya** [azukaar/Cosmos-Server#3]
### What happened?

 Frame overflow in cosmos-server (ServApps)

### What should have happened?

Go to the ServApps :)

### How to reproduce the bug?

Add a lot of networks

### Other details

When there are several networks:

![Screenshot 2023-04-08 at 15-16-48 Cosmos](https://user-images.githubusercontent.com/60230221/230723375-9e1e7d60-d6c1-4365-ba75-3d2cf0b5b51d.png)

### System details

Cosmos 0.1.12

**Comment by azukaar** [comment]
Fixed in v0.1.13

**Comment by zarevskaya** [comment]
Yep, cool, thank you!
