### ISSUE TITLE
[BUG]: im getting a red unlinked error

### ISSUE THREAD

**Issue by Gslgaming231** [azukaar/Cosmos-Server#304]
### What happened?

![Screenshot 2024-08-10 121503](https://github.com/user-attachments/assets/49f39924-f1fc-464e-b551-1c263d86ca42)

### What should have happened?

whenever i install cosmos it gives this error

**Comment by azukaar** [comment]
THis ticket needs (a lot) more infos. please provide some logs, your config, etc...
I'm closing the ticket until an actual bug can be identified. Feel free to comment again
