### ISSUE TITLE
[BUG]: Home Assistant automations are not saved

### ISSUE THREAD

**Issue by TobseF** [azukaar/Cosmos-Server#305]
### What happened?

In the Home Assists app, a newly created automation won't be saved.
The Wizard "New Automation" opens the save popup where I can set a name. Hitting "save" works -without an error. But the automation dashboard is still empty:
https://home-assistant/config/automation/dashboard

Seems to be a problem with the mounting point.

>  If your !include CONFIG_DIRECTORY is not the root directory of Home Assistant then the | wizard automations will never show up. The wizard only writes to ./automations.yaml (notice the “.” at the begining). The routine ignores the !include directive. Your automations are saved but never referenced.

The problem is also mentioned here:
https://community.home-assistant.io/t/automations-not-saving/155921/12newly

### What should have happened?

After saving a automation with the wizard, it should be shown on the automation page:
https://home-assistant/config/automation/dashboard
It should be activated and trigger the configured action. But it's not visible and won't be executed.

### How to reproduce the bug?

1. Install the Home Assistant app with default settings
2. Loing to Home Assistant
3. Got to the automation dashboard and press the blue "CREATE AUTOMATION" button.
4. Select "Create new automation"
5. Finis the Wizard and press "SAVE"
6. Give it a name and accept with "SAVE"
7. Open the automation dashboard again - and search for your freshly created automation

### System details

Image: lscr.io/linuxserver/homeassistant:latest
System: Raspi5

**Comment by azukaar** [comment]
Please open application specific ticket on the marketplace repo instead to keep this about cosmos itself (https://github.com/azukaar/cosmos-servapps-official )
ALthought looking at the ticket, it looks like its not related in anyway to Cosmos at all? Feel free to correct me if I misunderstood the issue

**Comment by kovacspityu** [comment]
Add line `automation: !include ./automations.yaml` to the /var/lib/docker/volumes/Home-Assistant-config/_data/configuration.yaml
