### ISSUE TITLE
Independent 3rd Party Security Code Audit

### ISSUE THREAD

**Issue by ggennrich** [azukaar/Cosmos-Server#314]
Curious if there are plans to have your code analyzed by a 3rd party? Given this is an all in one solution for homelabs it seems this should be prioritized to alleviate concerns over security and vulnerabilities. [HomeAssistant](https://www.home-assistant.io/blog/2023/10/19/security-audits-of-home-assistant/) which is an all in one solution for IoT has done this.

**Comment by azukaar** [comment]
Sure as long as the $$$ comes in, since this is a very expensive thing to do :)
