### ISSUE TITLE
[FEAT]: Paste Docker compose link option 

### ISSUE THREAD

**Issue by tarbib** [azukaar/Cosmos-Server#316]
### Feature Description

![Screenshot_20240908-230614](https://github.com/user-attachments/assets/850216c1-47b1-441a-ac81-61b6c6831023)
Hello 
It's great to have the upload option, I was wondering if we could have a "Docker compose link" option as well. 
This way we just point to the file hosted on github.com for example and it uploads directly form there. 
Thanks!

**Comment by azukaar** [comment]
I mean I get the idea but I feel like that's pushing it a little far :p 
I'm also concerned that people will paste links that have docker-compose files in them inside the page (ex. inside Pastebin or inside Github) and not just the docker compose itself
