### ISSUE TITLE
[BUG]: inconsistant naming

### ISSUE THREAD

**Issue by Ikarias** [azukaar/Cosmos-Server#32]
### What happened?

when updating a servapp, it is suddenly named serveapp

### What should have happened?

nothing, just wrong workind

### How to reproduce the bug?

1. goto servapp
2. 2. click update on any app.
3. low and behold

![cosmos term bug](https://github.com/azukaar/Cosmos-Server/assets/50828727/2d208b16-c4fd-4715-8c52-1e6679988dca)

### System details

OS: Linux Debian

**Comment by azukaar** [comment]
Good  catch thanks, will fix

**Comment by Ikarias** [comment]
No problem. Wish I could help lore, but in this regard I'm as tech savvy as whoever is going to replace ja k sparrow is in pirates....

**Comment by azukaar** [comment]
Fixed in 0.7.10
