### ISSUE TITLE
[FEAT]: set timezone

### ISSUE THREAD

**Issue by TasyDevilsky** [azukaar/Cosmos-Server#328]
### Feature Description

As a user I want to be able to set timezone, Because docker logs are in UTZ.
I have set using `timedatectl` correct timezone, but cosmos-cloud didn't respect that in UI ... 
When I start container with environment variable `TZ=Europe/Berlin` it works correctly in this specific container when you interactively mount into it, but cosmos-cloud UI still shows logs in UTZ.
- I also tried to change environment variable for `cosmos-server` container, but it isn't allowed.
![Screenshot from 2024-09-25 08-46-57](https://github.com/user-attachments/assets/d0de1631-14f6-44d7-b0f5-0c02d6b481b8)

**Comment by azukaar** [comment]
- Simply set the timezone on your server
- You can change the TZ on the Cosmos container, just not from Cosmos itself

**Comment by TasyDevilsky** [comment]
That's not entirely true, If you set your timezone on server using:
`timedatectl set-timezone "Europe/Berlin"` **cosmos-server** container will ignore that.
If you try to rewrite in `/var/lib/cosmos/cosmos.docker-compose.yml` environmental value to `   - TZ=Europe/Berlin` than when you restart your server the value will dissapear, probably because docker container still using it...

So I stopped cosmos-server container, removed it, edited `cosmos.docker-compose.yml` with timezone, and after that started container `cosmos-server` again, but it will delete the timezone value again.

So now I'm unsure where to change the timezone value so that the container doesn't overwrite it again.

**Comment by azukaar** [comment]
> cosmos-server container will ignore that.

How do you establish "ignore that"? If you are looking at other containers' logs the timestamp will still be wrong because those container have different TZ variables

> If you try to rewrite in /var/lib/cosmos/cosmos.docker-compose.yml environmental value to    - TZ=Europe/Berlin than when you restart your server the value will dissapear, probably because docker container still using it...

You cannot edit the container this way that's why, it's a backup it does not control the container. **you cannot edit the container by editing this file**

**Comment by TasyDevilsky** [comment]
My server have timezone set to `Europe/Berlin (CEST, +0200)` (by package `timedatectl`)
- When I run container `cosmos-server` it's in UTC <- I checked it via `docker exec -it ID_CONTAINER sh`
- When I start another container via cosmos I can set environmental variable ` -TZ=Europe/Berlin` and when I exec to this specific container the `date` output seems to correct. 
- What user can see in webUI in cosmos for example Logs its in UTC. Also on another containers which have already specified environmental variable is time in UTC. That's makes sense to me, because the `cosmos-server` container is responsible for showing the correct time.

_In overall I suppose that I need to change timezone in `cosmos-server` to be able to show correct timezone in webUI._
- So how can I correctly edit the container, or which file is responsible for that. Because `backup.cosmos-compose.json` aren't correct one too.

**Comment by azukaar** [comment]
Set the TZ to Europe/Berlin on the Cosmos container (inside the contianer it cannot read the host's TZ itself) then every app you install on the market will be given the right TZ automatically
