### ISSUE TITLE
[FEAT]: Use GitHub Actions for Full Build Transparency

### ISSUE THREAD

**Issue by tomtom215** [azukaar/Cosmos-Server#33]
### Feature Description

In the spirit of trusting an open/ available source project, I think it would be very helpful if you were able to use GitHub actions for this repo to complete your build, testing and release process so that users can verify the full tool-chain in an end to end manner.

**Comment by azukaar** [comment]
There's already a full CI/CD build that you can see, it is already fully transparent. Please check the CircleCI
