### ISSUE TITLE
[FEAT]: Alternative backend storage for containers

### ISSUE THREAD

**Issue by tech101us** [azukaar/Cosmos-Server#334]
### Feature Description

I know this can be a challenge given the sheer number of containers and configuration options out there. I love what you're doing with this. But the need I have is for alternative storage backends for container data (i.e. NFS, CIFS/Samba). Being able to store the data off host on a NAS for example is a welcome addition. Yes, we can do this manually either through bind mounts or in compose, but would be nice if it were a GUI option for the containers.

**Comment by azukaar** [comment]
#89
