### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by sylonweb** [azukaar/Cosmos-Server#342]
### What happened?

Hello everyone, many of the dockers that I installed when accessing from the home page, I get errors like:

ERR_CONNECTION_REFUSED
ERR_SSL_PROTOCOL_ERROR

### What should have happened?

The apps should open correctly

### How to reproduce the bug?

1. Install keycloak with defaults parameters
2. Open keycloak from home

### System details

- OS: Ubuntu 24.04.1 LTS 
- Browser: Brave
- Version :1.71.114

**Comment by azukaar** [comment]
Feel free to use the Discord or Reddit to get help on how to install specific app, but this is definitely not a bug.
Also please provide more logs are those are not complete enough to help you 
thanks!

**Comment by ThePastPlayer** [comment]
what did you do in order to solve this ? i'm getting the same bahavior on a fresh install, 'apps' install fine but some opens and some don't, same errors as you, can't pinpoint the issue either
