### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by wouterverduin** [azukaar/Cosmos-Server#36]
### What happened?

Attempted to setup cosmos on my productive server. Got about 25 containers running.

Setting up the container using the docker command from the website went without problems. At the webinterface at step 2 it is taking for about 2 hours now without any sign of progress.
It shows me these lines: 

`{"t":{"$date":"2023-06-26T14:24:52.363+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789492:363286][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 190, snapshot max: 190 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:25:52.371+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789552:370990][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 192, snapshot max: 192 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:26:52.380+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789612:380499][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 194, snapshot max: 194 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:27:52.387+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789672:387869][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 196, snapshot max: 196 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:28:52.398+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789732:398700][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 198, snapshot max: 198 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
`

### What should have happened?

Create a database and progress to step 3 in the setup

### Relevant log output

```shell
{"t":{"$date":"2023-06-26T14:24:52.363+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789492:363286][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 190, snapshot max: 190 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:25:52.371+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789552:370990][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 192, snapshot max: 192 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:26:52.380+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789612:380499][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 194, snapshot max: 194 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:27:52.387+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789672:387869][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 196, snapshot max: 196 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
{"t":{"$date":"2023-06-26T14:28:52.398+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1687789732:398700][1:0x7f0ca1c39700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 198, snapshot max: 198 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 7"}}
```

### Other details

Details from the cosmos-server container:

`2023/06/26 12:55:55 [INFO] Using config file: /config/cosmos.config.json
2023/06/26 12:55:55 [INFO] CheckUpdatesAvailable - Checking local image for change for containrrr/watchtower:latest
2023/06/26 12:55:55 [INFO] CheckUpdatesAvailable - No local updates available for containrrr/watchtower:latest
2023/06/26 12:55:55 [INFO] Checking for updates for portainer/portainer:latest
2023/06/26 12:55:56 [INFO] {"status":"Pulling from portainer/portainer","id":"latest"}
2023/06/26 12:55:56 [INFO] {"status":"Digest: sha256:47b064434edf437badf7337e516e07f64477485c8ecc663ddabbe824b20c672d"}
2023/06/26 12:55:56 [INFO] No updates available for portainer/portainer:latest
2023/06/26 12:55:56 [INFO] Using config file: /config/cosmos.config.json
2023/06/26 12:55:56 [INFO] CheckUpdatesAvailable - Checking local image for change for portainer/portainer:latest
2023/06/26 12:55:56 [INFO] CheckUpdatesAvailable - No local updates available for portainer/portainer:latest
2023/06/26 12:55:56 [INFO] Checking for updates for oznu/guacamole:latest
2023/06/26 12:55:57 [INFO] {"status":"Pulling from oznu/guacamole","id":"latest"}
2023/06/26 12:55:57 [INFO] {"status":"Digest: sha256:6268b3a08d9b3d71e1f8edfd593af95f0e1082b5f3d8649321b45c64e182a3a4"}
2023/06/26 12:55:57 [INFO] No updates available for oznu/guacamole:latest
2023/06/26 12:55:57 [INFO] Using config file: /config/cosmos.config.json
2023/06/26 12:55:57 [INFO] CheckUpdatesAvailable - Checking local image for change for oznu/guacamole:latest
2023/06/26 12:55:57 [INFO] CheckUpdatesAvailable - No local updates available for oznu/guacamole:latest
2023/06/26 13:02:23 "GET http://XX.XXX.XXX/ HTTP/1.1" from 124.220.161.119:33140 - 403 14B in 310.603µs
2023/06/26 13:22:48 [INFO] Cleaning up orphan networks...
2023/06/26 13:22:48 [INFO] Removing orphan network: stockpage_default
2023/06/26 13:22:48 [INFO] Removing orphan network: emulatorjs_default
2023/06/26 13:22:49 [INFO] Removing orphan network: reverseproxy-nw
2023/06/26 13:22:49 [INFO] Removing orphan network: paperless_default
2023/06/26 13:22:49 [INFO] Removing orphan network: cosmos-network-Cfsb8IYW1
`

### System details

ubuntu 22.04; Updated and running in docker.

**Comment by azukaar** [comment]
Would you mind retrying the setup and posting the entire log? Unfortunately the log you posted does not contain any information about this particular issue you are experiencing.
Make sure you clean the /var/lib/cosmos folder
