### ISSUE TITLE
[FEAT]: Setting Language

### ISSUE THREAD

**Issue by formeo14** [azukaar/Cosmos-Server#368]
### Feature Description

Currently, the Cosmos interface automatically defaults to the browser's language setting. For users whose browser language is set to English but prefer to use Cosmos in their native language, this behavior can be inconvenient. A feature to set the language preference in the Cosmos settings would allow users to override the browser language and choose their preferred language without needing to change their browser settings every time.

**Current Behavior:**
- The Cosmos interface language is always set to the browser's default language.
- If the browser language is English, the Cosmos interface will display in English, even if the user prefers another language.

**Desired Behavior:**
- Add a language setting in the Cosmos settings menu.
- Allow users to select their preferred language from a list of supported languages.
- The selected language should override the browser's default language and persist across sessions.

**Use Case:**
- A user whose browser language is set to English but prefers to use Cosmos in their native language (e.g., Spanish, French, German, etc.).
- The user does not want to change their browser language every time they use Cosmos and would prefer to set their language preference directly within the Cosmos settings.

**Comment by azukaar** [comment]
Click here

![image](https://github.com/user-attachments/assets/41e887f3-70e0-4608-9220-a4cdbdab9a76)

**Comment by formeo14** [comment]
@azukaar Does not work it will always be overwritten and again English

**Comment by azukaar** [comment]
It saves in the local storage. If your browser clear local storage that might happen, otherwise it should be persisted. It is also bound to your browser, not set for everyone at once
