### ISSUE TITLE
[BUG]: new install db error

### ISSUE THREAD

**Issue by lawmanuk** [azukaar/Cosmos-Server#374]
### What happened?

when installing db i get this error

{"errorDetail":{"message":"failed to register layer: write /usr/bin/mongostat: no space left on device"},"error":"failed to register layer: write /usr/bin/mongostat: no space left on device"}
Image mongo:4.4 pulled
Checking service cosmos-mongo-gkz...
Creating container cosmos-mongo-gkz...
[ERROR] Rolling back changes because of -- Container creation error: Error response from daemon: No such image: mongo:4.4

### What should have happened?

mongo db should have installed 

### How to reproduce the bug?

1. Go to clean install
2. Click on 'connect

### System details

- OS: void linux
- Browser firefox

**Comment by azukaar** [comment]
I think the error is pretty straightforward for you to solve no? "No space left" ?
