### ISSUE TITLE
[BUG]: LETSENCRYPT_DNS : unrecognized DNS provider: googledomains

### ISSUE THREAD

**Issue by arthurbrazil** [azukaar/Cosmos-Server#42]
### What happened?

`There are errors with your Let's Encrypt configuration or one of your routes, please fix them as soon as possible.:
- unrecognized DNS provider: googledomains`
Also terminal logs:
`2023/07/06 01:52:21 [ERROR] LETSENCRYPT_DNS : unrecognized DNS provider: googledomains
2023/07/06 01:52:21 [ERROR] Getting TLS certificate. Fallback to previous certificate : `

### What should have happened?

When I use Google Domains I get the above issue

### How to reproduce the bug?

Set Google Domain as provider.

**Comment by azukaar** [comment]
Fixed in 0.9.4 !

**Comment by GifHub123-GG** [comment]
I don't know what happened but the same bug seems to be happening in 0.9.16. I have the same exact error messages inside my logs while trying to use "googledomains" as my provider.
