### ISSUE TITLE
[BUG]: no matching manifest for arm/v8 (Not exactly a bug from you im afraid)

### ISSUE THREAD

**Issue by elchanly** [azukaar/Cosmos-Server#45]
### What happened?

When I execute cosmos in my Pi4b
`
NewInstall: Create DB
Starting creation of new service...
Pulling image arm64v8/mongo:4.4.18
4.4.18 Pulling from arm64v8/mongo 
{"errorDetail":{"message":"**no matching manifest for linux/arm/v8** in the manifest list entries"},"error":"no matching manifest for linux/arm/v8 in the manifest list entries"}
Image arm64v8/mongo:4.4.18 pulled
Checking service cosmos-mongo-kT0...
Forcing secure cosmos-mongo-kT0...`
This sometimes happens with other docker apps i try to install, my system seems to respond to linux/arm64.
I tried to add another db to docker-compose.yaml and it didnt work. 
What can I do, if something?
Thanks!

### What should have happened?

Cosmo DB created

### How to reproduce the bug?

Install on my system, im afraid..

### Relevant log output

```shell
NewInstall: Create DB
Starting creation of new service...
Pulling image arm64v8/mongo:4.4.18
4.4.18 Pulling from arm64v8/mongo 
{"errorDetail":{"message":"no matching manifest for linux/arm/v8 in the manifest list entries"},"error":"no matching manifest for linux/arm/v8 in the manifest list entries"}
Image arm64v8/mongo:4.4.18 pulled
Checking service cosmos-mongo-kT0...
Forcing secure cosmos-mongo-kT0...
```

### System details

Hardware: Raspberry Pi 4
OS: Raspberry Pi OS / x64 / 11 (bullseye)
Docker version 24.0.2, build cb74dfc
uname -m: aarch64

**Comment by azukaar** [comment]
Are you able to `docker pull arm64v8/mongo:4.4.18`?

**Comment by elchanly** [comment]
it throws no matching manifest for linux/arm/v8 in the manifest list entries :(

**Comment by azukaar** [comment]
Are you using Raspbian?
While your CPU is 64bit, Raspbian isn't arm64v8

**Comment by elchanly** [comment]
yes, is that the problem? i can use docker with arm64 images but not v8?
do i have to change raspbian to 64? if so, can i use 32 docker apps with rasp64?

**Comment by Eccomi21** [comment]
> > do i have to change raspbian to 64
> 
> Not sure if Raspbian is fully Arm64 but you can try

I'm sorry, I do not understand. [raspberrypi.com](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) states the following:
<html><body>
<!--StartFragment-->

Product | Processor | ARM core | Debian/Raspbian ARMport (maximum) | Architecture width
-- | -- | -- | -- | --
Raspberry Pi 4 | BCM2711 | Cortex-A72 | arm64 | 64 bit

<!--EndFragment-->
</body>
</html>

What do you mean when you say that Raspbian is maybe not “fully arm64”? Are we even talking about the same OS, given @elchanly stated in the bug report he is using Raspberry Pi OS as well, not Raspbian? (it is still based on Debian but y'know, it might be an important distinction).

The reason I am replying here is that I have a similar issue with `docker compose`.
When I paste the [provided docker-compose.yml](https://cosmos-cloud.io/doc/1%20index/)  and run it via `docker compose up` i get the following output:

```
docker@dataslate:~/cosmos$ docker compose up
[+] Running 10/10
 ✔ cosmos-server 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                                                                                           
   ✔ 34df401c391c Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 147bdf886518 Pull complete                                                                                                                                                                                                                                                                                        
   ✔ aa5b3a02a8e6 Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 1370825c7c0e Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 13e5a863955d Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 1c767f00d495 Pull complete                                                                                                                                                                                                                                                                                        
   ✔ beceb8e5acff Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 83cb9fd4104b Pull complete                                                                                                                                                                                                                                                                                        
   ✔ 3054d19d6b6e Pull complete                                                                                                                                                                                                                                                                                        
[+] Running 2/1
 ✔ Container cosmos-server                                                                                                                                      Created                                                                                                                                                15.5s
 ! cosmos-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                                                                                                         0.0s
Attaching to cosmos-server
cosmos-server  | standard_init_linux.go:219: exec user process caused: exec format error
cosmos-server exited with code 0
```

If I understand the warning there correctly, my host platform is arm64 v8, and I am able to `docker pull arm64v8/mongo:4.4.18`, which I did. This resolved the warning, but now instead of exiting with error code 0, the server exits with error code 1. the log spits out the following line on repeat: `standard_init_linux.go:219: exec user process caused: exec format error`

**Comment by azukaar** [comment]
That's a different issue, @Eccomi21 
Yours is because the docker-compose file on the  doc has :latest as a tag, you need to replace it with :latest-arm64

**Comment by Eccomi21** [comment]
It is always the simple things is it not... thank you! @azukaar
