### ISSUE TITLE
[FEAT]: Kubernetes support

### ISSUE THREAD

**Issue by Harnish** [azukaar/Cosmos-Server#46]
### Feature Description

K3s is super easy to get going and can easily scale beyond a single machine.  This would be awesome to support Kubernetes.

**Comment by azukaar** [comment]
This probably won't happen as K8's goals intersect and contradict some of Cosmos' own goals.
On one hand K8's feature set such as controlling the network layer intersect with Cosmos' own implementation
And on another hand, the premises of K8's large scale / corporate level feature set conflict directly with Cosmos' vision of simplicity for home servers

**Comment by Harnish** [comment]
I understand, I had to move to 2 machines because Photoprism was consuming a ton of resources causing delays in other services.

**Comment by azukaar** [comment]
Yes but Cosmos will supports multi-server on its own :)
