### ISSUE TITLE
[BUG]: Stack/Container Network gets modified by Cosmos

### ISSUE THREAD

**Issue by itguy327** [azukaar/Cosmos-Server#48]
### What happened?

this is my compose file with a macvlan and static ip. The static ip gets modified by Cosmos despite not making any changes using Cosmos. I still run Portainer and found Cosmos (awesome!) from selfh.st - Thank you

version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homenet
    networks:
      mymaclan:
        ipv4_address: 192.168.1.4
    volumes:
      - ./app/config:/app/config # Make sure your local config directory exists
      #- /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations

networks:
  mymaclan:
    external:
      name: mymaclan

### What should have happened?

my container ip should have remained 192.168.1.4

**Comment by azukaar** [comment]
I'm going to guess that the container does not show any sign of wanting to stay on a static IP in the docker API, so Cosmos does not know. The only way to fix it would be to have a new label cosmos-static-IP that forces an IP

Any reason why you are using static IPs? You can use the container name as hostname anyway with cosmos, as it forces it even when Docker loses it

**Comment by itguy327** [comment]
It does not maintain it's static IP, despite always having done so. My
reason for the static IP was to have more control via my firewall/pihole, I
use firewall rules and pihole groups to control internet access.

That being said, what does the label "cosmos-static-IP" do specifically,
where would I set that and do I need to change anything else in my compose
file (which is portainer/docker standard)

Also, what is the proxy being used in Cosmos, I currently use NPM and
have grown to like it but am interesting in potentially consolidating under
Cosmos.

Thank you again for your work.

Best Regards,
Jason

**Comment by azukaar** [comment]
Did you check "isolate network"? it is incompatible with custom network-modes

custom network-mode will work fine otherwise

The "cosmos-static-IP" does not exist at the moment, it was an hypothetical solution

>  what is the proxy being used in Cosmos

Cosmos is the proxy

**Comment by itguy327** [comment]
I did not check isolate network. Mainly because I was a bit confused on
what it would do to my existing config.

Is there documentation on advanced configuration on the proxy piece?

**Comment by azukaar** [comment]
Can you try using the name of the container instead of the API in pihole? Cosmos forces the network stack to use hostname in order to simplify the network management, so it should work (if you ever created / edited the container using Cosmos) let me know

**Comment by itguy327** [comment]
I have not edited with cosmos. Not certain how container name is the issue. My main issue is with my prior configuration not being honored. I was not even trying to use cosmos to modify it.

I run npm, portainer, watchtower currently and was looking to integrate cosmos and eventually replace all of that. 

Thank you

**Comment by azukaar** [comment]
Not container name, each container is given a hostname (which Cosmos forces to be the container name).
So basically, in pihole, instead of using 192.168.1.24, you can use the name of the container directly, ex "mycontainer") which will resolve to an IP, and this is the recommended way to use network routing in Docker in general

**Comment by krylon** [comment]
@itguy327 what OS were you using for this?

**Comment by itguy327** [comment]
I have docker & portainer running on Debian 11
Best Regards,
Jason Quackenbush
