### ISSUE TITLE
[HELP]: URL for ServApps remove additional public accessible ports

### ISSUE THREAD

**Issue by krylon** [azukaar/Cosmos-Server#50]
### What happened?

When creating a new URL for a servapp it disables all open ports except the one specified. I can understand how this is good for securing a web app but there are some containers where multiple external ports are still needed.

For example I was trying to create a url to a syslog server gui but I still need the various other ports open. More specifically this is for Graylog. Port 9000 is the web GUI, and I needed 1514/5041/514 to stay open for that container. I did not check the "isolate" option.

### What should have happened?

When the URL is created for a ServApp for a specific port do not remove the extra publicly available ports. Maybe an option?

### How to reproduce the bug?

1. Create graylog container (or perhaps any with multiple public ports)
2. Create URL for ServeApp, specify port of web gui
3. Under ServeApps observer only the web gui port is available

### Other details

- Removed URL and restarted container and ports do not come back
- Tried restarting Cosmos and ports do not come back
- Tried restarting server and ports do not come back
- Destroying and recreating the container will bring the ports back.
- Container is created outside of Cosmos (docker compose at command line)

### System details

- OS: Docker Version 24.0.4 (using docker compose)
- Browser: Edge
- Version: 9.8

**Comment by azukaar** [comment]
Hello!
It should not do this. The current behaviour is what you described: if you create a URL in a container with already exposed ports, they will stay exported.
The only thing that un-expose ports is the "isolate network" checkbox. Also please note that your container needs to be connected to the bridge network, and in bridge network mode to be able to keep port exposed, may be that's your issue?

**Comment by krylon** [comment]
This is what appears to happen. When I create a URL Cosmos creates a random network for both containers to communicate on, cosmos-network-random. Once it's attached to the destination container I lose all of my ports except the one I configured in the URL, port 9000.
![cosmos1](https://github.com/azukaar/Cosmos-Server/assets/14024346/547e6765-d790-44ba-b2ed-c1918dd85b3c)


I built a new VM, DietPi OS v8.19, Current Docker, Cosmos v0.9.8 and Graylog v5.1 and can reproduce this issue. I dont know if this is relevant but any network that is already in bridge mode still has an error in cosmos that says it isnt.

**Comment by krylon** [comment]
FWIW this might just be a Graylog container problem. Im still troubleshooting.

**Comment by azukaar** [comment]
Ahhh wait but that's a logic issue I think
I am not sure 100% but I think if you set the network mode to be a specific network, then you cannot connect a second network at all. May be that's why Docker is reverting your changes when Cosmos tries to connect its own network

**Comment by krylon** [comment]
I dont want to clutter this with another problem but this could possibly a separate issue. I noticed under the ServApp->Container->Details->Networks the "Network Mode = network name generated from the container start instead of the network driver.

If I change this to "bridge" I dont get that network error I posted earlier. 

![network-mode](https://github.com/azukaar/Cosmos-Server/assets/14024346/ed03915a-01b5-4886-a425-6bd518c31f34)

I am still troubleshooting the ports. I used another whoami container and 3 published ports and do not have a similar problem as with the graylog container. Id love if anyone could verify this for me and Id be more than happy to provide me compose file.

**Comment by krylon** [comment]
> Yes that is what I was telling you earlier, you are using a container/network name as a network mode, which is valid but act very differently than normal Docker setups, and I was asking you why you were doing this Normally you only do this to use VPN on your containers for example, by making a container the network driver

I wasnt specifying any network in the compose file and just let it do its own when bringing up the container initially. When I deploy Cosmos for the first time it creates a network called "cosmos_default" and applies it to the Network Mode. Is this intended? Not trying to be difficult here, just trying to understand why my network names keep appearing in the network mode box.

![cosmos-network-mode](https://github.com/azukaar/Cosmos-Server/assets/14024346/6dc9aaf3-9d77-44c9-aff0-65b16711c321)

**Comment by azukaar** [comment]
No it is not inteded, the "cosmos_default" network, is not something cosmos does, cosmos is in bridge mode if you just run in a vanilla Docker environment, that's why I was asking about it, because it confuses me too! :)
