### ISSUE TITLE
[FEAT]: Update Cosmos

### ISSUE THREAD

**Issue by Serph91P** [azukaar/Cosmos-Server#52]
### Feature Description

Would be great if one could Update cosmos from within the interface. So one would not need to pull the docker again.

**Comment by azukaar** [comment]
Guessing that from closing this ticket you found the update button :D
For anyone finding this from Googling: there's an update button on the container from the servapp tab

**Comment by Serph91P** [comment]
> Guessing that from closing this ticket you found the update button :D For anyone finding this from Googling: there's an update button on the container from the servapp tab

Yep only thing was it kinda went offline after pressing the update button. Thanks

**Comment by azukaar** [comment]
It's an issue with docker-compose creating network in the background. Sometime it fails to be disconnected properly

Run `docker network disconnect cosmos-server cosmos-server_default`
