### ISSUE TITLE
[BUG]: own Nextcloud container

### ISSUE THREAD

**Issue by Serph91P** [azukaar/Cosmos-Server#53]
### What happened?

installed cosmos after I already started with some container.
Nextcloud is reporting that the webserver is not doing this: https://docs.nextcloud.com/server/27/admin_manual/issues/general_troubleshooting.html#service-discovery

### What should have happened?

those entries are forwarded correctly

### System details

- OS: Ubuntu 22.04
- Browser Firefox
- Version 115.0.2

**Comment by azukaar** [comment]
Did you setup Nextcloud using the market? If yes it is doing this, just try to hit the caldav URL it will work
If not you need to setup the redirections yourself by creating URLs
