### ISSUE TITLE
[BUG]: Environment variables can't contain equals symbol

### ISSUE THREAD

**Issue by jwr1** [azukaar/Cosmos-Server#54]
### What happened?

I'm trying to set up a docker container that requires the use of "=" in the environment variable's value, but Cosmos seems to have a hard time with that. Setting up with either a cosmos config or manually doesn't seem to work. Also if you try to edit it in later, it disappears on save.

### What should have happened?

Environment variables should be able to contain any characters, so I expect the equals symbol to be treated as any other.

### How to reproduce the bug?

1. Go to the "ServApps" page.
2. Click on "Start ServApps".
3. Click on "Add" under the "Environment Variables" section.
4. Try to type an equals symbol in the "Value" field and it will disappear almost instantly. 

### System details

- OS: Arch Linux
- Browser: Firefox 115.0.2
- Version: 0.9.10

**Comment by azukaar** [comment]
Fixed in Released with 0.9.11 thanks you!
