### ISSUE TITLE
Vaultwarden with Smart Shield

### ISSUE THREAD

**Issue by Serph91P** [azukaar/Cosmos-Server#57]
### What happened?

Cannot Sync but can login. As soon as you try to sync with an app it fails but you can login just fine. As far as I understand it you get rate limited. Already increased the Maximum number of requests Per Minute.

### What should have happened?

Apps Sync just fine.

### How to reproduce the bug?

open bitwarden app in settings press synchronize.

If you disable Smart Shield it synchronizes just fine.

### System details

All of them tried Linux Windows and Android.

**Comment by azukaar** [comment]
Could you give me the exact log from the smart shield? May be the client is making simultaneous request
Just to know what exactly gets you rate limited

**Comment by Serph91P** [comment]
> Could you give me the exact log from the smart shield? May be the client is making simultaneous request Just to know what exactly gets you rate limited

It blocked my IP. Will search for the log again.did not save it.

**Comment by Serph91P** [comment]
> Could you give me the exact log from the smart shield? May be the client is making simultaneous request Just to know what exactly gets you rate limited

this is the log said:

```
2023/07/25 15:37:32 [INFO] SmartShield: Request received
2023/07/25 15:37:32 [INFO] SmartShield: User is blocked due to abuse: &{ClientID:134.3.170.212 banType:0 time:{wall:13918328361448459235 ext:13436926450495 loc:0x4e92380} reason:{ClientID:134.3.170.212 Time:80.370862705 Requests:12271 Bytes:62611 Simultaneous:0} out of {Enabled:true PolicyStrictness:2 PerUserTimeBudget:7.2e+06 PerUserRequestLimit:6000 PerUserByteLimit:161061273600 PerUserSimultaneous:24 MaxGlobalSimultaneous:250 PrivilegedGroups:2}}
```

**Comment by azukaar** [comment]
Your request limit is still at 6000? that's the default value, are you sure you have increased it?

**Comment by Serph91P** [comment]
> Your request limit is still at 6000? that's the default value, are you sure you have increased it?
> 
> either way please try with 0.9.13 I have made changes to the shield and see if you still get the issue

yep I upgraded the limit, but now I cannot access the cosmos ui at all got a red symbol when trying to access the ui. 
![image](https://github.com/azukaar/Cosmos-Server/assets/8904984/40ff9933-afe5-4fd1-a4f6-244a1909929b)

**Comment by Serph91P** [comment]
> Your request limit is still at 6000? that's the default value, are you sure you have increased it?
> 
> either way please try with 0.9.13 I have made changes to the shield and see if you still get the issue

Vaultwarden is working again, thanks to the logs I think I found the culprit. Is the connection request limit global? For multiple domains, because my IP got blocked again but for another container.

**Comment by Serph91P** [comment]
> connection request limit global is the max number of IP that can request at once, is this running a public service? But that limit does not block IPs it just refuses new requests until others have completed

No it's not public per se. As you can see above the log says IP is blocked ban type 0. It didn't even open that url that day and still got blocked. My guess it since it is global all applications are above the 12k limit wherever it is set and then my IP gets blocked. Maybe a whitelist or something would be great.

**Comment by azukaar** [comment]
"banType:0" Means it's a strike (a 1h ban)
And yes before 0.9.13 the user request count was global but since 0.9.13 it is not anymore


PS: Also you need to make sure your network is reporting the right IP "ClientID:redacted " and not some proxy IP for example, where every users would have the same IP because the source IP is not preserved

**Comment by Serph91P** [comment]
> "banType:0" Means it's a strike (a 1h ban) And yes before 0.9.13 the user request count was global but since 0.9.13 it is not anymore
> 
> PS: Also you need to make sure your network is reporting the right IP "ClientID:redacted " and not some proxy IP for example, where every users would have the same IP because the source IP is not preserved

Yeah I removed it because it was my IP ;)

**Comment by azukaar** [comment]
OK I will close the issue for now, and let me know if you still get blocked on 0.9.13
