### ISSUE TITLE
[FEAT]: Use Cosmos as a OIDC Server

### ISSUE THREAD

**Issue by DrMxrcy** [azukaar/Cosmos-Server#6]
### Feature Description

As a User, I would like to integrate apps that have SSO Support with protocols like OIDC or SAML to use Cosmos as the Authentication Provider. Alterative to using a Keycloak, Authelia, Authentik, etc.

**Comment by azukaar** [comment]
OIDC is definitly a high priority item as it will enable many developers to integrate (mobiles / desktops) applications with Cosmos.

For SAML I have something else in mind, but I would like to prototype it before exposing it. Essentially SAML has a very limited number of servers apps supporting it, and I need to find a way to cover most server apps with a unified login (I have a good idea how, I just need time to test it out ;) )

**Comment by azukaar** [comment]
Added OIDC to 0.6.0
closing the ticket, as SAML support is not planned as for now
