### ISSUE TITLE
[BUG]: [ERROR] Rolling back changes because of -- Route already exist

### ISSUE THREAD

**Issue by nvadave** [azukaar/Cosmos-Server#60]
### What happened?

I installed WordPress from the Market, removed it, and tried to install it again. During the creation process I get the following error.

> [ERROR] Rolling back changes because of -- Route already exist

How do I find and delete the route? 

### What should have happened?

I expected WordPress to install without issue.

### How to reproduce the bug?

1. Install WordPress from the Market
2. Remove Wordpress
3. Reinstall WordPress from the Market
4. [ERROR] Rolling back changes because of -- Route already exist

### System details

- OS: Ubuntu 22.04
- Cosmos 0.9.13
- Browser: Firefox

**Comment by nvadave** [comment]
I was able to find and remove the route in /var/lib/cosmos/cosmos.config.json

WP installed as expected.

**Comment by azukaar** [comment]
You find all the routes in the URL tab on the left side menu :)

**Comment by nvadave** [comment]
Thank you!
