### ISSUE TITLE
Error:  The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

### ISSUE THREAD

**Issue by GD-Dal** [azukaar/Cosmos-Server#61]
Hi.
I'm getting this message when trying to install cosmos-server:
` The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

Is the PI I'm trying to install on just too old, or is there a way around this?

Thanks

**Comment by azukaar** [comment]
Sorry it only supports more recent versions of the Rasp, it might be possible to make it work on ARM v7 but I do not have one to test on, so the image is built for V8
