### ISSUE TITLE
[FEAT]: Support header based authentication

### ISSUE THREAD

**Issue by jwr1** [azukaar/Cosmos-Server#66]
### Feature Description

I'd like Cosmos to have support for header-based authentication, which is used in several applications like FireflyIII, Snipe-IT, and probably others. Basically, Cosmos would need an option to set headers for the username and email when signed in (and maybe redirect to Cosmos when signed out), these could either be hardcoded as `REMOTE_USER` and `REMOTE_USER_EMAIL` respectively, or we could allow users to modify them. I'd assume these would be options under each URL's settings since headers directly correlate to the routes. For reference [here's](https://docs.firefly-iii.org/firefly-iii/advanced-installation/authentication#remote-user-authentication) the page for implementing this sort of remote authentication with FireflyIII, and [here's](https://tools.ietf.org/html/rfc3875#section-4.1.10) the RFC that documents the header.

I can definitely help with the implementation if you'd like. I'd probably be a little slower though as I don't have experience with go (most of what I do is JS/TS/node).

**Comment by azukaar** [comment]
This is suppoorted as x-cosmos-user and x-cosmos-role, you can use the var AUTHENTICATION_GUARD_HEADER  to tell firefly where to look for this value

**Comment by jwr1** [comment]
That's awesome! Didn't realize this already existed. Is there also a header for the email as well, or is it just the username?

**Comment by azukaar** [comment]
Just for the username, for privacy reason I didnt want to leak the email address
