### ISSUE TITLE
[BUG]: Issue with googledomains DNS provider popping backup

### ISSUE THREAD

**Issue by Ronald-Diemicke** [azukaar/Cosmos-Server#69]
### What happened?

So like in #42 - this appears to be an issue again:

Getting this:
2023/08/08 21:08:33 [ERROR] LETSENCRYPT_DNS : unrecognized DNS provider: googledomains
2023/08/08 21:08:33 [ERROR] Getting TLS certificate. Fallback to previous certificate : 

### What should have happened?

I'd have expected to see this validate with google domains instead of falling back...

### How to reproduce the bug?

Use google domains

### Relevant log output

```shell
2023/08/08 21:08:33 [ERROR] LETSENCRYPT_DNS : unrecognized DNS provider: googledomains
2023/08/08 21:08:33 [ERROR] Getting TLS certificate. Fallback to previous certificate :
```

### System details

Running Cosmos in an unraid container

**Comment by azukaar** [comment]
Fixed in 0.9.17
