### ISSUE TITLE
[FEAT]: Cosmos Tunnels

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [azukaar/Cosmos-Server#7]
### Feature Description

Hi,
One major issue with reverse proxies is opening up ports and exposing your home IP address to the internet. Using a VPS to route traffic is a significant upgrade in terms of security. 
Integrating a wireguard tunnel to communicate with the NAS would make sure no ports need to be exposed and have a secure connection between the NAS and VPS, and your home IP address is not exposed either.
A similar project is boringproxy, but it lacks the 2FA feature, DNS based certs and other features that Cosmos seems to have.

**Comment by azukaar** [comment]
This is indeed in the roadmap, thanks for showing interest in this feature!
I don't know yet the details, but I want Cosmos servers to be able to communicate with each other, so that not only you can tunnel your connections, but also manage all your cosmos instances from one UI

**Comment by damomato** [comment]
Not sure if related, but would this also allow something like gluetun to run containers through VPN services?

**Comment by SteaceP** [comment]
In the meantime you can use Cloudflare Tunnels

**Comment by Gandalf-the-Blue** [comment]
> In the meantime you can use Cloudflare Tunnels

For a more privacy respecting experience, I would recommend boringproxy

**Comment by SteaceP** [comment]
> For a more privacy respecting experience, I would recommend boringproxy

I just pointed out something that have everything you wanted until Cosmos add tunnels.
I don't understand peoples with privacy, they have phones, on top of it a Facebook account to name a few. Your privacy is already out the window and big times.

**Comment by Gandalf-the-Blue** [comment]
Hi @azukaar is there any update on this?

**Comment by azukaar** [comment]
> Hi @azukaar is there any update on this?

2 in facts :) it's all in the Discord

**Comment by Gandalf-the-Blue** [comment]
oh, I don't use discord. Is there an ETA available?

**Comment by azukaar** [comment]
Current ETA is another 5-6 weeks for inital release, which will be a free open beta for everyone to try Constellation and give feedback

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/d13ea5c6-e463-4df3-808d-8da22cfd82c7)

**Comment by Gandalf-the-Blue** [comment]
Does this include websocket support?
Also, are wildcard certificates supported?
Also what does Beacons mean? Does this mean that the tunnel won't be able to bypass CGNATs? So a VPS can't connect to a home server behind a CGNAT?

**Comment by azukaar** [comment]
Websockets have been supported since day 1
Wildcard certificate for a long time too

Those 2 things are not related to tunnels

Beacons is what enables bypassing CGNAT so yes it will be able to

**Comment by grigio** [comment]
Yeah not everybody has a public ip accessible from outside, dns over VPN and bypass cgnat is a pain

**Comment by azukaar** [comment]
Forgot to close this ticket :D
Now Cosmos has Constellation (since 0.10.0) and you can bypass CGNAT with it. Just have 2 Cosmos running (master at home with the "private" option, and a $5 digital ocean with the lighthouse option on) and connect your devices to access your server via tunnel.
More info in the doc

**Comment by Gandalf-the-Blue** [comment]
Hey,
Saw the progress. Great work!
Just had 1 question - In the docs I saw a list of clients to connect to the network. Does this mean there is no setting available to just use the VPN as a relay, i.e. to not have to use clients to connect to the network and instead expose the page on the internet?

**Comment by Gandalf-the-Blue** [comment]
Hi @azukaar - I finally got around to trying cosmos now that Constellation is live and well.
In the initial steps, I see that server needs to have the domain IP pointed to it. 

Is this setup possible?

1. Home NAS behind CGNAT.
2. Public VPS with domain pointed to it.
3. Set up Cosmos on VPS
4. Run Containers on NAS & expose them via the VPS?

**Comment by azukaar** [comment]
Yes absolutely, the trick is to enable the "override host" option on the VPS so that the home servers sees the request as if they were direct request:

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/f4681bfb-f518-483a-ab0f-465193ced47e)

More here (bottom of the page): 

https://cosmos-cloud.io/doc/5%20URLs
