### ISSUE TITLE
[BUG]: ServApp Routes that are not defined as 'admin only' are not available to normal users

### ISSUE THREAD

**Issue by Ronald-Diemicke** [azukaar/Cosmos-Server#73]
### What happened?

So the user permissions model seems to need some work because "users" can only see proxy routes and such that you haven't required admin rights for; but ServApp routes won't appear for "users" at all regardless of if you've specified if they're for an admin or not.

### What should have happened?

I'd expect all routes to be available to users unless specified as a route that's admin only.

### How to reproduce the bug?

1. Create a route for a ServApp
2. Create a user
3. Login as that user, notice the ServApp route isn't available

### System details

- OS: Unraid
- Browser: Chrome

**Comment by azukaar** [comment]
Thanks for report! Fixed in 0.9.19
