### ISSUE TITLE
[FEAT]: Search ServApps by container ID

### ISSUE THREAD

**Issue by tarbib** [azukaar/Cosmos-Server#75]
### Feature Description

In Servapps menu, I would like to be able to search by container ID in order to  quickly retrieve the Servapps.

**Comment by azukaar** [comment]
Do you mean the docker id like "oidofh9df8h9ahdf98ashd9fha9d8fh9ahdf98ahsdf"  ?

**Comment by tarbib** [comment]
Yes indeed!

**Comment by azukaar** [comment]
Not sure exactly where that would fit in since the ID is not even shown in the UI tbh
I mean i can add it, it's a one line change but I dont really see the point to be honest ^^

**Comment by tarbib** [comment]
![Screenshot_20230812_225239_Firefox](https://github.com/azukaar/Cosmos-Server/assets/2255433/f69d1b72-1077-49ae-81c1-84b8d1f7c24d)
This is the container ID right?
My use case : I was debugging. I could not remove a network because it said it still had endpoints or something.
I found a command to retrieve the container ID linked to the network. At this moment I would have liked to simply copy and paste it in cosmos and analyse the situation from the ServApp.

**Comment by azukaar** [comment]
Understood make sense!

**Comment by azukaar** [comment]
Done in 0.13
