### ISSUE TITLE
[FEAT]: OpenID with Azure

### ISSUE THREAD

**Issue by MephistoJB** [azukaar/Cosmos-Server#82]
### Feature Description

I use the Azure AD very excessive. Any chance to get it running with Comos? Or is it already possible?

**Comment by azukaar** [comment]
Mid to Low chances -- someone started working on it on a fork, I will merge  it if it works well and meet the criteria
but from my perspective this is not a high priority item as Cosmos itself is already an ID provider so I won't work on it myself, at least not in the forseable future

**Comment by MephistoJB** [comment]
Thx for your answer. Do you know which fork it is, maybe I can assist

**Comment by azukaar** [comment]
https://github.com/EvanTrow/Cosmos-Server
