### ISSUE TITLE
[FEAT]: Host a static application (SFTP) access if possible.

### ISSUE THREAD

**Issue by ccjcan** [azukaar/Cosmos-Server#83]
### Feature Description

Hello, I'm enjoying Cosmos so far, was able to install and running a few containers.
I'd like to host a simple static website, likely in /home/<username>/www, should be behind authentication and if possible have access via SFTP. I'm used to YunoHost, this would be similar to their My Custom Web app.
I'd appreciate if anyone could point me in the right direction.

**Comment by azukaar** [comment]
When you go to URL, you can create a URL of type "static" to show a static site
(if said static site is an SPA, you can also create a URL of type SPA)

**Comment by ccjcan** [comment]
I’d like to host the static app on the same server, do you recommend a simple folder www with index.html (for example) or a container with nginx?)

**Comment by azukaar** [comment]
Static URL take a folder not a container as an argument, so you can put the folder anywhere and set the arg to the /path (make sure it is mounted of course, or use /mnt/host/... to access a folder on your host)

![image](https://github.com/azukaar/Cosmos-Server/assets/7872597/4e5ea305-dd3c-4906-b5d6-529235f1ca85)
