### ISSUE TITLE
[BUG]: Filebrowser doesnt have access to download folder

### ISSUE THREAD

**Issue by mareczek82** [azukaar/Cosmos-Server#84]
### What happened?

Hello,

I installed filebrowser and metube and audiobookshelf from cosmos market. 
I wanted to move files from download location to audiobook folder, but i cannot access to download folder or any other folder created by other docker app. 

### What should have happened?

I thought that i could use filebrowser to manage files on my VPS. 

### How to reproduce the bug?
COSMOS, and all dockers were installed with default settings. 

![image](https://github.com/azukaar/Cosmos-Server/assets/97781683/b2ecfb74-46d8-4c0a-9808-ecfc23e27686)
Its in Polish, it says that I don't have permission to have access. 

2023/08/23 14:25:33 /usr/downloads/: 403 [my ip]open /srv/usr/downloads: permission denied

### System details

- OS: [e.g. iOS] UBUNTU 22 LTS on ARM based Oracle free tier VPS
- Browser [e.g. chrome, safari] Chrome

**Comment by tarbib** [comment]
Hello @mareczek82 ! I have the same issue with permission error on some folders
Did you find a solution?
Thanks

**Comment by azukaar** [comment]
If you want to make sure Filebrowser has access to everything you can change the PID and GID in the env var of the container from 1000 to 0
Otherwise you need to make sure that your first user account has permission to access the folder you want to access
