### ISSUE TITLE
[BUG]: Re instalation of filebrowser

### ISSUE THREAD

**Issue by mareczek82** [azukaar/Cosmos-Server#87]
### What happened?

As I had issue with accessing to folders created by other docker apps [i](https://github.com/azukaar/Cosmos-Server/issues/84) wanted to recreate Filebrowser hoping it will override access permissions. 
I killed this docker, then deleted it via ServApps. Then I tried to instal it via Marked but I can't. 

this is log from installation cli

> Creating Service...                              
> Starting creation of new service...
> Pulling image filebrowser/filebrowser:s6
> s6 Pulling from filebrowser/filebrowser 
> {"status":"Digest: sha256:a6da98e2ce087e69062dae368675afaef9d084a65735224d7fe4cc6237c83bb0"}
> {"status":"Status: Image is up to date for filebrowser/filebrowser:s6"}
> Image filebrowser/filebrowser:s6 pulled
> Checking service Filebrowser...
> Forcing secure Filebrowser...
> Created secure network cosmos-network-136YfTDSM
> Creating container Filebrowser...
> Checking directory /mnt/host/usr/Filebrowser/Filebrowser-database.db for bind mount
> Checking directory /mnt/host/usr/Filebrowser/.Filebrowser-filebrowser.json for bind mount
> Checking directory /mnt/host/ for bind mount
> [ERROR] Rolling back changes because of -- Route already existRolled back container Filebrowser
> Rolled back network cosmos-network-136YfTDSM
> [OPERATION FAILED]. CHANGES HAVE BEEN ROLLEDBACK.

Any ideas how to fix this? I don't want broke my cosmos setup. 

### What should have happened?

Filebrowser app should be installed

### How to reproduce the bug?

1. Go to 'ServApps and delete old docker..'
2. Click on 'Market'
3. Scroll down to 'Filebrowser' and create new docker

### System details

OS: [e.g. iOS] UBUNTU 22 LTS on ARM based Oracle free tier VPS
Browser [e.g. chrome, safari] Chrome

**Comment by azukaar** [comment]
You need to clean up the route in the URL tab before reinstalling (removing file browser)
a better re-install journey will be worked on soon
