### ISSUE TITLE
[BUG]: "patch" method is prohibited in Cosmos middleware

### ISSUE THREAD

**Issue by k00lagin** [azukaar/Cosmos-Server#90]
### What happened?

Some third-party selfhosted services (like Pocketbase) rely on PATCH requests, which are [not allowed](https://github.com/azukaar/Cosmos-Server/blob/525146a2102ecede8b59931121ab8688e6baa674/src/utils/middleware.go#L85) by Cosmos middleware. So when app tries to use such request it fails due to MethodDisallowedByPreflightResponse error.

### What should have happened?

Patch requests should be passed through middleware as any other requests.

### How to reproduce the bug?

1. Go to any service working through Cosmos
2. Open Devtools on the Network tab
3. Examine response headers of any random request to the service itself
4. Find header Access-Control-Allow-Methods
5. See that the list of methods is restricted to "GET, POST, PUT, DELETE, OPTIONS"

### System details

- Cosmos: 0.9.21

**Comment by azukaar** [comment]
Good catch thanks will fix

**Comment by azukaar** [comment]
Fixed
