### ISSUE TITLE
[FEAT]: Add somewhere to request additional DNS providers

### ISSUE THREAD

**Issue by SiJiL82** [azukaar/Cosmos-Server#96]
### Feature Description

My domain is currently with Hostinger, their DNS provider is `dns-parking.com` 
That's not available in the list of providers - it would be useful if there was a way to request additions to the provider list, even if that results in a rejection if they don't support required features for example.

**Comment by azukaar** [comment]
Cosmos is using the Let's Encrypt bot with https://github.com/go-acme/lego
They would need to implemente it first, before I can add support. Feel free to create a request there :)
