### ISSUE TITLE
[FEAT]: Configure icons

### ISSUE THREAD

**Issue by mikrofyr** [azukaar/Cosmos-Server#99]
### Feature Description

Would like to be able to configure custom icons for URLs.
Seems there is some way by label for docker images. It is a bit uncovenient, and does not support proxy URL as far as I understand.

PS: Great application!

**Comment by plangin** [comment]
Why is this closed? Seems like it still not possible to define custom icons for Proxy URLs.

Tested on Cosmos Server 0.16.3
